/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uni.intense.vue;

import com.uni.intense.presentation.IEtudiants;
import com.uni.intense.presentation.InterfaceNote;
import com.uni.intense.service.BulletinHtmlEtudiant;
import com.uni.intense.service.ServiceInterNet;
import com.uni.intense.service.ServiceReseau;
import com.uni.intense.service.TransformerPortraitPdf;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kelly
 */
public class FenBulletin extends javax.swing.JInternalFrame {
ServiceReseau ser=new ServiceReseau();

    /**
     * Creates new form FenBulletin
     */
    public FenBulletin() {
          initComponents();
          panbulletin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxniveau = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxsession = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtCodeEt = new javax.swing.JTextField();
        btnbulletin = new javax.swing.JButton();
        panbulletin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNom = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lblmoy = new javax.swing.JLabel();
        lbloptions = new javax.swing.JLabel();
        lblvacation = new javax.swing.JLabel();
        lblpromotion = new javax.swing.JLabel();
        btnpdf = new javax.swing.JButton();
        btnemail = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Niveau: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 62, -1, -1));

        cbxniveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbxniveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxniveauActionPerformed(evt);
            }
        });
        jPanel1.add(cbxniveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 59, 82, -1));

        jLabel3.setText("Session :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 62, -1, -1));

        cbxsession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cbxsession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsessionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxsession, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 59, 104, -1));

        jLabel1.setText("Code Etudiant :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 62, -1, -1));
        jPanel1.add(txtCodeEt, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 59, 161, -1));

        btnbulletin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnbulletin.setText("Voir Bulletin");
        btnbulletin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbulletinActionPerformed(evt);
            }
        });
        jPanel1.add(btnbulletin, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 99, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, 885, -1));

        panbulletin.setBackground(new java.awt.Color(255, 255, 255));
        panbulletin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cours", "Notes", "Sur", "Reprises 1", "Reprises 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panbulletin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 651, 267));

        lblNom.setText("Nom:");
        panbulletin.add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        lblPrenom.setText("Prenom:");
        panbulletin.add(lblPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        lbltotal.setText("Total :");
        panbulletin.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        lblmoy.setText("Moyenne :");
        panbulletin.add(lblmoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        lbloptions.setText("Options :");
        panbulletin.add(lbloptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        lblvacation.setText("Vacation :");
        panbulletin.add(lblvacation, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        lblpromotion.setText("Promotion :");
        panbulletin.add(lblpromotion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        btnpdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf_24px.png"))); // NOI18N
        btnpdf.setText("Imprimer");
        btnpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpdfActionPerformed(evt);
            }
        });
        panbulletin.add(btnpdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnemail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find_email_24px.png"))); // NOI18N
        btnemail.setText("Envoyer Ce Bulletin");
        btnemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemailActionPerformed(evt);
            }
        });
        panbulletin.add(btnemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        getContentPane().add(panbulletin, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 189, 870, 360));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 890, 50));

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 204, 204));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bulletin Etudiant");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 24, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 885, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxniveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxniveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxniveauActionPerformed

    private void cbxsessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxsessionActionPerformed
     int bulletin(String Niv, String CodeEtud, String session) throws NamingException, RemoteException {
             
            int permis = 0;
             Context cont=new InitialContext();
        IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
            permis=mato.verifierpaie( Niv,  CodeEtud,  session);
            if (permis == 0)
            {
                  JOptionPane.showMessageDialog(this,"cette Etudiant a une dette pour cette session","Erreur",JOptionPane.ERROR_MESSAGE);
             
            }
            else if (permis == 1) {}
            return permis;
        }
    private void btnbulletinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbulletinActionPerformed
   try {
        // TODO add your handling code here:
        
        String CodeEt=txtCodeEt.getText().trim();
        if(CodeEt.isEmpty()){
              JOptionPane.showMessageDialog(null,"Entrer le code ","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            Context cont=new InitialContext();
        IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
        ArrayList<String> Fiche;
        Fiche=mato.FicheEtudiant(CodeEt);
     String   Id_Etud=Fiche.get(0);
     if(CodeEt.equals(Id_Etud)){
   //   System.out.println("code la  bon");
  
      String codeniv=cbxniveau.getSelectedItem().toString();
        String codesession=cbxsession.getSelectedItem().toString();
        String NomVacation=Fiche.get(11);
      String Promotion=Fiche.get(13);
    
     
        // System.out.println("l'option est "+Nomopt);
 
        
          
           InterfaceNote mati=(InterfaceNote) cont.lookup(ser.getNote());
            ArrayList<String> RechercherBulletin;   
            RechercherBulletin=mati.RechercherBulletin(codeniv, codesession, Id_Etud);
            String Options=RechercherBulletin.get(0);
           
            //    System.out.println("l'option est "+Options);
            String Groupe=RechercherBulletin.get(1);
                String Exer=RechercherBulletin.get(2);
            
            String Nom=RechercherBulletin.get(5);
            String Prenom=RechercherBulletin.get(6);
  
            String Total1=RechercherBulletin.get(8);
            String Total2=RechercherBulletin.get(9);
            String Moyenne=RechercherBulletin.get(10);
            double m=Double.parseDouble(Moyenne);
            String moyenne2=String.format("%.2f", m);
            lblNom.setText("Nom: "+Nom);
            lblPrenom.setText("Prenom: "+Prenom);
            lbltotal.setText("Total "+Total1+" Sur "+Total2);
            lblmoy.setText("Moyenne "+moyenne2+" Sur 10 ");
            lbloptions.setText("Options: "+Options);
            lblvacation.setText("Vacation: "+Groupe);
            lblpromotion.setText("Promotion: "+Exer);
            if(Moyenne.equals("0.0")){
              JOptionPane.showMessageDialog(null,"Cet Etudiant ne contient pas de notes dans aucun Palmares de ce niveau et cette Session","Erreur",JOptionPane.ERROR_MESSAGE);
           panbulletin.setVisible(false);
            }
            else{
            listerBulletin(Options, codeniv, codesession, Id_Etud, NomVacation, Promotion);
             panbulletin.setVisible(true);
            }
            
            
             
     }
     
     else{
        JOptionPane.showMessageDialog(null,"Le code est incorect","Erreur",JOptionPane.ERROR_MESSAGE);
           panbulletin.setVisible(false);
     }
        }
    
     
    } catch (NamingException | RemoteException ex) {
        Logger.getLogger(FenBulletin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnbulletinActionPerformed

    private void btnpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpdfActionPerformed
        // TODO add your handling code here:
       // TODO add your handling code here:
   try {
        // TODO add your handling code here:
  
        String CodeEt=txtCodeEt.getText().trim();
             String codeniv=cbxniveau.getSelectedItem().toString();
        String codesession=cbxsession.getSelectedItem().toString();
         int var = bulletin(codeniv, CodeEt, codesession);
            if (var == 1)
            {
        Context cont=new InitialContext();
        IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
        ArrayList<String> Ficha;
        Ficha=mato.FicheEtudiant(CodeEt);
     String   Id_Etud=Ficha.get(0);
     if(CodeEt.equals(Id_Etud)){
     // System.out.println("code la  bon");
   
 
        String NomVacation=Ficha.get(11);
      String Promotion=Ficha.get(13);
      
           
       int niv2=Integer.parseInt(codeniv);
        
      
           InterfaceNote mati=(InterfaceNote) cont.lookup(ser.getNote());
           
            
            ArrayList<String> RechercherBulletin=new ArrayList<>();    
            RechercherBulletin=mati.RechercherBulletin(codeniv, codesession, Id_Etud);
            String Options=RechercherBulletin.get(0);
            String Groupe=RechercherBulletin.get(1);
                String Exer=RechercherBulletin.get(2);
                        int ex=Integer.parseInt(Exer);
                        int ext= ex+niv2;
                        int ext2=ex+niv2-1;
             String Exercice=ext2+"-"+ext;
             String Session=RechercherBulletin.get(3);
            String Niveau=RechercherBulletin.get(4);
            String Nom=RechercherBulletin.get(5);
            String Prenom=RechercherBulletin.get(6);
            String Matricule=RechercherBulletin.get(7);
            String Total1=RechercherBulletin.get(8);
            String Total2=RechercherBulletin.get(9);
            String Moyenne=RechercherBulletin.get(10);
             double m=Double.parseDouble(Moyenne);
            String moyenne2=String.format("%.2f", m);
                                     String [][] maliste=mati.ListerBulletin(Options, codeniv, codesession, Id_Etud, NomVacation, Promotion);
                String td="";
            String tr1="<tr>";
            String tr2="</tr>";
          //  int v=0;
            ArrayList Fiche=new ArrayList();
            for (String[] maliste1 : maliste) {
                Fiche.add(tr1);
            for (String maliste11 : maliste1) {
                td = "<td>" + maliste11 + "</td>";
                Fiche.add(td);
            }
                Fiche.add(tr2);
            }
            String Fiche2=Fiche.toString();
            String Fiche3=Fiche2.replace(",", "");
            String Fiche4=Fiche3.replace("[", "");
            String   Tbody=Fiche4.replace("]", "");  
                       BulletinHtmlEtudiant dd=new BulletinHtmlEtudiant();
             String Html=dd.BulletinHtmlEtudiant(Options, Niveau, Session, Exercice, Nom, Prenom, Matricule, Groupe, Total1, Total2, moyenne2, Tbody);
                        TransformerPortraitPdf pdf=new TransformerPortraitPdf();
                        
                      int s=  pdf.TransformerPortraitPdf(Html, "Bulletin"+Options);
                     switch (s) {
             case 0:
                  JOptionPane.showMessageDialog(this,"une erreur est survenu veuillez reessaye","Erreur",JOptionPane.ERROR_MESSAGE);
                 break;
                 case 1:
                  JOptionPane.showMessageDialog(this,"le bulletin a ete cree en pdf avec succes \n  mais il semblerait qu'une erreur est survenu nous n'avons pas pu le lancer automatique"
                          + " \n  allez dans C: src  pour ouvrir le fichier","Attention",JOptionPane.WARNING_MESSAGE);
                 break;
             default:
                  JOptionPane.showMessageDialog(this,"Bulletin creer avec succes","Succes",JOptionPane.INFORMATION_MESSAGE);
         }
      
     }
     
     else{
         System.err.println("code la pa bon"+CodeEt+Id_Etud);
     }
            }
    } catch (NamingException | IOException ex) {
        Logger.getLogger(FenBulletin.class.getName()).log(Level.SEVERE, null, ex);
    }     
          
    }//GEN-LAST:event_btnpdfActionPerformed

    private void btnemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemailActionPerformed
        // TODO add your handling code here:
         try {
        // TODO add your handling code here:
        
        String CodeEt=txtCodeEt.getText().trim();
             String codeniv=cbxniveau.getSelectedItem().toString();
        String codesession=cbxsession.getSelectedItem().toString();
         int var = bulletin(codeniv, CodeEt, codesession);
            if (var == 1)
            {
        Context cont=new InitialContext();
        IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
        ArrayList<String> Ficha;
        Ficha=mato.FicheEtudiant(CodeEt);
     String   Id_Etud=Ficha.get(0);
     if(CodeEt.equals(Id_Etud)){
      System.out.println("code la  bon");
   
 
        String NomVacation=Ficha.get(11);
      String Promotion=Ficha.get(13);
     
       int niv2=Integer.parseInt(codeniv);
    
         
           InterfaceNote mati=(InterfaceNote) cont.lookup(ser.getNote());
           
            
            ArrayList<String> RechercherBulletin;    
            RechercherBulletin=mati.RechercherBulletin(codeniv, codesession, Id_Etud);
            String Options=RechercherBulletin.get(0);
            String Groupe=RechercherBulletin.get(1);
                String Exer=RechercherBulletin.get(2);
                        int ex=Integer.parseInt(Exer);
                        int ext= ex+niv2;
            int ext2=ex+niv2-1;
             String Exercice=ext2+"-"+ext;
             String Session=RechercherBulletin.get(3);
            String Niveau=RechercherBulletin.get(4);
            String Nom=RechercherBulletin.get(5);
            String Prenom=RechercherBulletin.get(6);
            String Matricule=RechercherBulletin.get(7);
            String Total1=RechercherBulletin.get(8);
            String Total2=RechercherBulletin.get(9);
            String Moyenne=RechercherBulletin.get(10);
            double ma=Double.parseDouble(Moyenne);
            String moyenne2=String.format("%.2f", ma);
                                     String [][] maliste=mati.ListerBulletin(Options, codeniv, codesession, Id_Etud, NomVacation, Promotion);
                String td="";
            String tr1="<tr>";
            String tr2="</tr>";
          //  int v=0;
            ArrayList Fiche=new ArrayList();
            for (String[] maliste1 : maliste) {
                System.out.println("<tr>");
                Fiche.add(tr1);
          for (String maliste11 : maliste1) {
              System.out.println("<td>" + maliste11 + "</td>");
              td = "<td>" + maliste11 + "</td>";
              Fiche.add(td);
          }
                Fiche.add(tr2);
                System.out.println("</tr>");
            }
            String Fiche2=Fiche.toString();
            String Fiche3=Fiche2.replace(",", "");
            String Fiche4=Fiche3.replace("[", "");
            String   Tbody=Fiche4.replace("]", "");  
                       BulletinHtmlEtudiant dd=new BulletinHtmlEtudiant();
             String Html=dd.BulletinHtmlEtudiant(Options, Niveau, Session, Exercice, Nom, Prenom, Matricule, Groupe, Total1, Total2, moyenne2, Tbody);
                        
                        ServiceInterNet m=new ServiceInterNet();
                           String expediteur = "laguerrekelly.k@gmail.com".trim();
                            String sujet="Bulletien de "+Session;
                          String mes=   m.envoyerEmail(Html,expediteur,sujet);
                          
                              JOptionPane.showMessageDialog(this,mes,"Information",JOptionPane.INFORMATION_MESSAGE);
      
     }
     
     else{
         System.err.println("code la pa bon"+CodeEt+Id_Etud);
     }
            }
    } catch (NamingException | IOException ex) {
        Logger.getLogger(FenBulletin.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_btnemailActionPerformed

    void listerBulletin(String Nom_Opt,String codeniv,String codesession,String Id_Etud,String NomVacation, String Promotion) throws NamingException, RemoteException{
                     
                   Context cont=new InitialContext();
          InterfaceNote mati=(InterfaceNote) cont.lookup(ser.getNote());
            String [][] maliste=mati.ListerBulletin(Nom_Opt, codeniv, codesession, Id_Etud, NomVacation, Promotion);
String[] titre= {"Cours", "Notes","Sur","Reprises 1","Reprises 2"};
 DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbulletin;
    private javax.swing.JButton btnemail;
    private javax.swing.JButton btnpdf;
    private javax.swing.JComboBox<String> cbxniveau;
    private javax.swing.JComboBox<String> cbxsession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblmoy;
    private javax.swing.JLabel lbloptions;
    private javax.swing.JLabel lblpromotion;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel lblvacation;
    private javax.swing.JPanel panbulletin;
    private javax.swing.JTextField txtCodeEt;
    // End of variables declaration//GEN-END:variables
}
