/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uni.intense.vue;

import com.uni.intense.presentation.InterfaceEmployer;
import com.uni.intense.presentation.InterfaceUtilisateur;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ServiceReseau;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

/**
 *
 * @author kelly
 */
public class fenCreerUtilisateur extends javax.swing.JInternalFrame {
   ServiceReseau ser=new ServiceReseau();
Contrainte co=new Contrainte();

String code;
    /**
     * Creates new form fenCreerUtilisateur2
     */
    public fenCreerUtilisateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodeRechercher = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtFonction = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomUser = new javax.swing.JTextField();
        jPFMotPasse = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, -1, -1));

        txtCodeRechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodeRechercherKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodeRechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 22, 248, -1));

        btnRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnRechercher.setText("Rechercher");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });
        jPanel1.add(btnRechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 22, 203, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 527, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information de l'employe"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Code");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, -1, -1));

        jLabel3.setText("Nom");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 80, -1, -1));

        jLabel4.setText("Prenom");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 27, -1, -1));

        jLabel5.setText("Fonction");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        txtcode.setEditable(false);
        jPanel2.add(txtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 24, 152, -1));

        txtnom.setEditable(false);
        jPanel2.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 77, 152, -1));

        txtPrenom.setEditable(false);
        jPanel2.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 24, 216, -1));

        txtFonction.setEditable(false);
        jPanel2.add(txtFonction, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 77, 217, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 527, -1));

        jLabel6.setText("Nom Utilisateur");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 256, -1, -1));

        jLabel7.setText("Mot de Passe");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 256, -1, -1));
        getContentPane().add(txtNomUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 253, 134, -1));
        getContentPane().add(jPFMotPasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 253, 154, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add-User-icon.png"))); // NOI18N
        jButton1.setText("Creer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 293, 520, -1));

        jPanel4.setBackground(new java.awt.Color(25, 118, 211));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ajouter Utilisateur");
        jPanel4.add(jLabel9);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
void renitialiser(){
       txtCodeRechercher.setText("");     
    txtcode.setText("");
            txtnom.setText("");
            txtPrenom.setText("");
            txtFonction.setText("");
               txtNomUser.setText("");
                  jPFMotPasse.setText("");
}
    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        try {
            // TODO add your handling code here:

            code=txtCodeRechercher.getText().trim();
            if(code.isEmpty()){
                JOptionPane.showMessageDialog(null,"Code Vide","Erreur",JOptionPane.ERROR_MESSAGE);

            }
            else{
               
                Context cont=new InitialContext();
                InterfaceEmployer mato=(InterfaceEmployer) cont.lookup(ser.getEmploye());
                ArrayList<String> FicheEmployer=new ArrayList<>();
                FicheEmployer=mato.FicheEmployer(code);
                String Code2=FicheEmployer.get(0);
                if(Code2!=null){
                    txtcode.setText(FicheEmployer.get(0));
                    txtnom.setText(FicheEmployer.get(1));
                    txtPrenom.setText(FicheEmployer.get(2));
                    txtFonction.setText(FicheEmployer.get(10));
                }
                else{
                    JOptionPane.showMessageDialog(null,"Le code est incorect","Erreur",JOptionPane.ERROR_MESSAGE);
                    renitialiser();
                }
            }
        } catch (NamingException ex) {
            Logger.getLogger(fenCreerUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(fenCreerUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRechercherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:

            String nomuser,code,retour,statut,etat;
            char[] motpasse;
            code=txtcode.getText().trim();
            motpasse=jPFMotPasse.getPassword();
            String motepasse2=String.valueOf(motpasse);
            nomuser=txtNomUser.getText().trim();
            if(code.isEmpty()){
                JOptionPane.showMessageDialog(null,"Effectuez Avant Tout Une Rechercher","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else  if(nomuser.isEmpty()||motepasse2.isEmpty()){
                JOptionPane.showMessageDialog(null,"Remplissez les champs vides","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else  if(motepasse2.length()<5){
                JOptionPane.showMessageDialog(null,"le mot de passe doit contenir au minimum 4 caracteres","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else{
                Context cont=new InitialContext();
                
                InterfaceUtilisateur mato=(InterfaceUtilisateur) cont.lookup(ser.getUtilisateur());
                String message=mato.EnregistrerUtilisateur(code, nomuser, motepasse2);
                JOptionPane.showMessageDialog(fenCreerUtilisateur.this,message);
                renitialiser();
            }
        } catch (NamingException ex) {
            Logger.getLogger(fenCreerUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(fenCreerUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodeRechercherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeRechercherKeyTyped
        // TODO add your handling code here:
        co.isletterdigit(evt);
    }//GEN-LAST:event_txtCodeRechercherKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFMotPasse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCodeRechercher;
    private javax.swing.JTextField txtFonction;
    private javax.swing.JTextField txtNomUser;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
