/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uni.intense.vue;

import com.uni.intense.presentation.IEtudiants;
import com.uni.intense.presentation.InterfaceService;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ImageFilterJava;
import com.uni.intense.service.ServiceInterNet;
import com.uni.intense.service.ServiceReseau;
import com.uni.intense.service.TransfererFichier;
import java.awt.Image;
import java.io.File;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author kelly
 */
public class FenEnregisterEtudiants extends javax.swing.JInternalFrame {
ServiceReseau ser=new ServiceReseau();
;
private String dateNaiss;
private String filename;
private String filename1;
ServiceInterNet s=new ServiceInterNet();
String Images="src//Image//personne2.png";
Contrainte d=new Contrainte();
    /**
     * Creates new form FenInscrireEtudiant
     */
    public FenEnregisterEtudiants() {
        initComponents();
           rempliroptions();
        dada();
        afficherImage(Images);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomRespon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPhoneRespon = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadresse = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxoptioncours = new javax.swing.JComboBox<>();
        cbxvacation = new javax.swing.JComboBox<>();
        txtNif = new javax.swing.JFormattedTextField();
        cmbSexe = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        btnupload = new javax.swing.JButton();
        panetu = new javax.swing.JPanel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomRespon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomResponKeyTyped(evt);
            }
        });
        getContentPane().add(txtNomRespon, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 116, 208, -1));

        jLabel10.setText("Phone Responsable");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 159, -1, -1));

        try {
            txtPhoneRespon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+509 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtPhoneRespon, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 156, 210, -1));

        jLabel9.setText("Nom Responsable ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 119, -1, -1));

        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+509####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 308, 210, -1));

        jLabel8.setText("Phone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 311, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 184, 210, -1));

        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 187, -1, -1));

        jScrollPane1.setViewportView(txtadresse);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 370, 210, 110));

        jLabel6.setText("Adresse");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 370, -1, -1));

        jLabel11.setText(" Options");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 394, -1, -1));

        getContentPane().add(cbxoptioncours, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 391, 195, -1));

        cbxvacation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matin", "Median", "Soir", "Week-End" }));
        getContentPane().add(cbxvacation, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 330, 194, -1));

        try {
            txtNif.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 268, 194, -1));

        cmbSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculin", "Feminin" }));
        getContentPane().add(cmbSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 178, 194, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add-User-icon.png"))); // NOI18N
        jButton1.setText("Inscrire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 486, -1, -1));

        jLabel14.setText("Vacation");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 333, -1, -1));

        jLabel13.setText("Nif / Cin");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 268, -1, -1));

        txtPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrenomKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 150, 194, -1));

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomKeyTyped(evt);
            }
        });
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 116, 194, -1));

        jLabel5.setText("Date Naissance");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 206, -1, -1));

        jLabel4.setText("Sexe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 181, -1, -1));

        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 150, -1, -1));

        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 119, -1, -1));
        getContentPane().add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 116, 259, 259));

        btnupload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_24px.png"))); // NOI18N
        btnupload.setText("choisir image");
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });
        getContentPane().add(btnupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 393, -1, -1));

        panetu.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inscriptions Etudiant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(jLabel12)
                .addContainerGap(474, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panetuLayout = new javax.swing.GroupLayout(panetu);
        panetu.setLayout(panetuLayout);
        panetuLayout.setHorizontalGroup(
            panetuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panetuLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panetuLayout.setVerticalGroup(
            panetuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panetuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(126, 126, 126)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );

        txtDate.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(panetu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 530));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 530, 1150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
final void afficherImage(String urlphoto){
ImageIcon  icon=new ImageIcon(urlphoto);
      Image image=icon.getImage().getScaledInstance(259, 259, Image.SCALE_SMOOTH);
      icon = new ImageIcon(image);
       lblimage.setIcon(icon);
}
    void rempliroptions(){
 try {
                    
             
                    ArrayList<String> Al=new ArrayList<>();
                    Context cont=new InitialContext();
                  InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
                    Al=  mato.remplirComboOptions();
                     int i=0;
        for(String dep:Al)
        {
           
            cbxoptioncours.addItem(dep);
            
            i++;
        }
                } catch (NamingException ex) {
                    Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
                }
}
void dada(){
    String datenai="2000/12/31";
           String datenai2="1950/01/30";
           try {
            
            Date date=new SimpleDateFormat("yyyy/MM/dd").parse(datenai);
      txtDate.setMaxSelectableDate(date);
       txtDate.setDate(date);
        } catch (ParseException ex) {
            
        }
             
           try {
            
            Date date=new SimpleDateFormat("yyyy/MM/dd").parse(datenai2);
      txtDate.setMinSelectableDate(date);
        } catch (ParseException ex) {
            
        }
}
    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    void renitialiser(){
 txtEmail.setText("");
   txtNif.setText("");
     txtNom.setText("");
    txtNomRespon.setText("");
    txtPhone.setText("");
    txtPhoneRespon.setText("");
    txtPrenom.setText("");
    txtadresse.setText("");
     cbxoptioncours.setSelectedIndex(0);
     cbxvacation.setSelectedIndex(0);
     cmbSexe.setSelectedIndex(0);
     filename=null;
     filename1=null;
  afficherImage(Images);
     
     
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
      
            // TODO add your handling code here:

            String Nom=txtNom.getText().trim().replace("'", "''");
            String Prenom =txtPrenom.getText().trim().replace("'", "''");
            String Sexe =cmbSexe.getSelectedItem().toString();

            int dola=0;
            try{
                Date dd = txtDate.getDate();
                DateFormat format=new SimpleDateFormat("yyyy/MM/dd");
                dateNaiss = format.format(dd);
                dola=1;
            }
            catch(Exception ex){

                dola=0;
            }

            String Nif = txtNif.getText().trim();
            String Adresse =txtadresse.getText().trim().replace("'", "''");
            String Email =txtEmail.getText().trim();
            String Phone =txtPhone.getText().trim();
            String NomResponsable =txtNomRespon.getText().trim().replace("'", "''");
            String PhoneResponsable =txtPhoneRespon.getText().trim();
            String Vacation =cbxvacation.getSelectedItem().toString();
            String NomOption =cbxoptioncours.getSelectedItem().toString().replace("'", "''");
            boolean verif=s.isValid(Email);
            if(Nom.isEmpty()||Prenom.isEmpty()||Adresse.isEmpty()||Email.isEmpty()||NomResponsable.isEmpty()){
                JOptionPane.showMessageDialog(null,"Tous les champs doivent etres remplis","Erreur",JOptionPane.ERROR_MESSAGE);
            }else if(Nom.length()<2||Prenom.length()<2||NomResponsable.length()<2){
                JOptionPane.showMessageDialog(null,"les champs noms et prenoms et Nom des responsable ne doivent pas inferieur a un caractere","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else if(Nif.length()<12){
                JOptionPane.showMessageDialog(null,"Le Cin doit contenir 10 Chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else if(Phone.length()<13||PhoneResponsable.length()<13){
                JOptionPane.showMessageDialog(null,"Les Telephones doivent avoir plus de avoir 8 chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
            }

            else if(dola==0){
                JOptionPane.showMessageDialog(null,"Mettre une date de naissance","Erreur",JOptionPane.ERROR_MESSAGE);
            }
              else if(verif==false){
                JOptionPane.showMessageDialog(null,"Cet Email n'est pas valide","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else    if(filename==null||filename1==null){
               JOptionPane.showMessageDialog(null,"Choisissez une photo","Erreur",JOptionPane.ERROR_MESSAGE);
           }
            else{
                Context cont=new InitialContext();
                IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
                String gu= mato.EnregistrerEtudiant(Nom, Prenom, Sexe, dateNaiss, Nif, Adresse, Email, Phone, NomResponsable, PhoneResponsable, Vacation, NomOption);
                   TransfererFichier img=new TransfererFichier();
   String fe = FilenameUtils.getExtension(filename);
                 String Code="Img"+gu+"."+fe;
          String url=   img.EnvoyerFichier(filename, filename1,Code);

          mato.ModifierUrlPhoto(gu, url);
             JOptionPane.showMessageDialog(FenEnregisterEtudiants.this,"Etudiant Inscris Avec Succes");
             renitialiser();
            }

        }catch (NamingException | RemoteException ex) {
            Logger.getLogger(FenEnregisterEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser=new JFileChooser();
         chooser.addChoosableFileFilter(new ImageFilterJava());
            chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();

             filename=f.getAbsolutePath();
            filename1=f.getName();
           
            afficherImage(filename);
                }
                catch(Exception e){
                filename=null;
                filename1=null;
                      afficherImage(Images);
                }
        
    }//GEN-LAST:event_btnuploadActionPerformed

    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtNomKeyPressed

    private void txtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyTyped
        d.isletter(evt);
    }//GEN-LAST:event_txtNomKeyTyped

    private void txtPrenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrenomKeyTyped
        // TODO add your handling code here:
        d.isletter(evt);
    }//GEN-LAST:event_txtPrenomKeyTyped

    private void txtNomResponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomResponKeyTyped
        // TODO add your handling code here:
        d.isletter(evt);
    }//GEN-LAST:event_txtNomResponKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupload;
    private javax.swing.JComboBox<String> cbxoptioncours;
    private javax.swing.JComboBox<String> cbxvacation;
    private javax.swing.JComboBox<String> cmbSexe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JPanel panetu;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtNif;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNomRespon;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JFormattedTextField txtPhoneRespon;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextPane txtadresse;
    // End of variables declaration//GEN-END:variables
}
