/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uni.intense.vue;

import javax.swing.JPanel;

/**
 *
 * @author kelly
 */
public class FenExamen extends javax.swing.JInternalFrame {

    /**
     * Creates new form FenExamen2
     */
    public FenExamen() {
        initComponents();
        
                JPanel FenlisterPalmares=new PanlisterPalmares();
            JPanel eval =new PanEvaluation();
                 JPanel t =new PanPalmares();
                     JPanel PanNotes =new PanNotes();
      
           jTabbedPaneMenu.addTab(" Gestion Palmares", t);
          jTabbedPaneMenu.addTab("Gestion Evaluation", eval);
          jTabbedPaneMenu.addTab("Gestion Notes", PanNotes);
           jTabbedPaneMenu.addTab(" Liste des Evaluation d'un Palmares", FenlisterPalmares);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMenu = new javax.swing.JTabbedPane();

        setClosable(true);
        setIconifiable(true);

        jTabbedPaneMenu.setPreferredSize(new java.awt.Dimension(1220, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    // End of variables declaration//GEN-END:variables
}
