/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uni.intense.vue;

import com.uni.intense.presentation.InterfaceEmployer;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.DocFilterJava;
import com.uni.intense.service.ImageFilterJava;
import com.uni.intense.service.ServiceInterNet;
import com.uni.intense.service.ServiceReseau;
import com.uni.intense.service.TransfererFichier;
import java.awt.Image;
import java.io.File;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author kelly
 */
public class FenGestionEmployer extends javax.swing.JInternalFrame {
 ServiceReseau ser=new ServiceReseau();
 ServiceInterNet s=new ServiceInterNet();
Contrainte co=new Contrainte();

private String code;

      String nom,prenom,sexe,nif,adresse,telephone,email,DateNaissance,fonction,Statut; 
      private String filenameImg;
private String nameImg;
private String urlphoto;
private String urldoc;
private String filenamedoc;
private String namedoc;
String Images="src//Image//personne2.png";
    /**
     * Creates new form fenEmbaucherEmploye2
     */
    public FenGestionEmployer() {
        initComponents();
           dada();
              rdbrech.setSelected(false);
         btnembaucher.setVisible(true);
         btnrechercher.setVisible(false);
         btnmodifier.setVisible(false);
          btnupload.setVisible(true);
        btnmodifimg.setVisible(false);
            btnmodifcv.setVisible(false);
               btnmodifcv.setVisible(false);
                btnopendoc.setVisible(false);
       afficherImage(Images);
         remplirfonction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        cmbSexe = new javax.swing.JComboBox();
        mskNif = new javax.swing.JFormattedTextField();
        txtAdresse = new javax.swing.JTextField();
        mskTelephone = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbSatut = new javax.swing.JComboBox();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        Salaire = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbFonction = new javax.swing.JComboBox();
        spnSalaire = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        btnembaucher = new javax.swing.JButton();
        btnrechercher = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        rdbenreg = new javax.swing.JRadioButton();
        lblimage = new javax.swing.JLabel();
        btnuploadDoc = new javax.swing.JButton();
        btnmodifcv = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rdbrech = new javax.swing.JRadioButton();
        btnupload = new javax.swing.JButton();
        btnmodifimg = new javax.swing.JButton();
        btnopendoc = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Personnelle"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 58, -1, -1));

        jLabel2.setText("Sexe");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 153, -1, -1));

        jLabel3.setText("Adresse");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 240, -1, -1));

        jLabel4.setText("DateNaissance");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 405, -1, -1));

        jLabel5.setText("Prenom");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 101, -1, -1));

        jLabel6.setText("Cin :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 200, -1, -1));

        jLabel7.setText("Telephone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 301, -1, -1));

        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 357, -1, -1));

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomKeyTyped(evt);
            }
        });
        jPanel1.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 55, 240, -1));

        txtPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrenomKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 98, 240, -1));

        cmbSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculin", "Feminin" }));
        jPanel1.add(cmbSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 150, 240, -1));

        try {
            mskNif.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(mskNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 197, 240, -1));
        jPanel1.add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 237, 240, -1));

        try {
            mskTelephone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+509)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(mskTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 298, 240, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 354, 240, -1));

        jLabel9.setText("Statut :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 470, -1, -1));

        cmbSatut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celibataire ", "En Couple" }));
        jPanel1.add(cmbSatut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 240, -1));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 400, 510));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Administrative"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salaire.setText("Salaire");
        jPanel2.add(Salaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 128, -1, -1));

        jLabel10.setText("Fonction");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 62, -1, -1));

        jPanel2.add(cmbFonction, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 59, 158, -1));
        jPanel2.add(spnSalaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 125, 158, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnembaucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add-User-icon.png"))); // NOI18N
        btnembaucher.setText("Embaucher");
        btnembaucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnembaucherActionPerformed(evt);
            }
        });

        btnrechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnrechercher.setText("Rechercher");
        btnrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherActionPerformed(evt);
            }
        });

        btnmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit-icon.png"))); // NOI18N
        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnmodifier)
                        .addGap(64, 171, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnembaucher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrechercher)
                        .addGap(31, 31, 31))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnembaucher)
                    .addComponent(btnrechercher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnmodifier)
                .addGap(22, 22, 22))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 110, 350, 514));

        rdbenreg.setSelected(true);
        rdbenreg.setText("Enregistrer");
        rdbenreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbenregActionPerformed(evt);
            }
        });
        getContentPane().add(rdbenreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 72, -1, -1));
        getContentPane().add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 142, 259, 259));

        btnuploadDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file_doc.png"))); // NOI18N
        btnuploadDoc.setText("Choisir CV");
        btnuploadDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnuploadDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 544, -1, -1));

        btnmodifcv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update_file_24px.png"))); // NOI18N
        btnmodifcv.setText("Modifier CV");
        btnmodifcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifcvActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodifcv, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 544, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdbrech.setText("Rechercher");
        rdbrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbrechActionPerformed(evt);
            }
        });
        jPanel4.add(rdbrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 59, -1, -1));

        btnupload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_24px.png"))); // NOI18N
        btnupload.setText("Choisir Image");
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });
        jPanel4.add(btnupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 457, -1, -1));

        btnmodifimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Camera-icon.png"))); // NOI18N
        btnmodifimg.setText("Modifier Image");
        btnmodifimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifimgActionPerformed(evt);
            }
        });
        jPanel4.add(btnmodifimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 461, -1, -1));

        btnopendoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/file-person-icon.png"))); // NOI18N
        btnopendoc.setText("Ouvrir le document");
        btnopendoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopendocActionPerformed(evt);
            }
        });
        jPanel4.add(btnopendoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 602, -1, -1));

        jPanel5.setBackground(new java.awt.Color(25, 118, 211));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gestion Employer");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addComponent(jLabel12)
                .addContainerGap(501, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(15, 15, 15))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 630));

        jPanel6.setBackground(new java.awt.Color(25, 118, 211));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 void dada(){
    String datenai="2000/12/31";
           String datenai2="1950/01/30";
           try {
            
            Date date=new SimpleDateFormat("yyyy/MM/dd").parse(datenai);
      txtDate.setMaxSelectableDate(date);
       txtDate.setDate(date);
        } catch (ParseException ex) {
            
        }
             
           try {
            
            Date date=new SimpleDateFormat("yyyy/MM/dd").parse(datenai2);
      txtDate.setMinSelectableDate(date);
        } catch (ParseException ex) {
            
        }
}
 void renitialiser(){
txtnom.setText("");
             txtPrenom.setText("");
             cmbSexe.setSelectedItem("Masculin");
             mskNif.setText("");
             txtAdresse.setText("");
             mskTelephone.setText("");
       
             txtEmail.setText("");
             cmbSatut.setSelectedItem("Celibataire");
             cmbFonction.setSelectedItem("Secretaire");
          
            spnSalaire.setValue(0);
            filenameImg=null;
        nameImg=null;
        urlphoto=null;
        urldoc=null;
         filenamedoc=null;
        namedoc=null;
        code=null;
          afficherImage(Images);
}
      String verifsalaire(int salaire) {
          String message="erreur";
     try {
         String nomfonction=cmbFonction.getSelectedItem().toString();
         ArrayList<String> Al;
         Context cont=new InitialContext();
         InterfaceEmployer mato=(InterfaceEmployer) cont.lookup(ser.getEmploye());
         Al = mato.recherchersalaire(nomfonction);
         int salaire_mini = Integer.parseInt(Al.get(0));
         int salaire_maxi= Integer.parseInt(Al.get(1));
         
          if(salaire<salaire_mini){
  message= "Salaire Minimum pour "+nomfonction+" "+salaire_mini;
            }
            else if (salaire > salaire_maxi)
            {
                  message="Salaire Maximum pour " + nomfonction + " " + salaire_maxi;
            }
          else {
                    message=null;  

     }
     } catch (NamingException | RemoteException ex) {
         Logger.getLogger(FenGestionEmployer.class.getName()).log(Level.SEVERE, null, ex);
     }
      return message;
     }
    
    final void remplirfonction(){
 try {
                    
                
                    ArrayList<String> Al;
                    Context cont=new InitialContext();
                  InterfaceEmployer mato=(InterfaceEmployer) cont.lookup(ser.getEmploye());
                    Al=  mato.remplirCombofonction();
                     int i=0;
        for(String dep:Al)
        {
           
            cmbFonction.addItem(dep);
            
            i++;
        }
                } catch (NamingException | RemoteException ex) {
                    Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
                }
}
    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void btnembaucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnembaucherActionPerformed

        int salaire;
        nom=txtnom.getText().trim().replace("'", "''");
        prenom=txtPrenom.getText().trim().replace("'", "''");
        sexe=cmbSexe.getSelectedItem().toString();
        nif=mskNif.getText().trim();
        adresse=txtAdresse.getText().trim().replace("'", "''");
        telephone=mskTelephone.getText().trim();
        email=txtEmail.getText().trim().replace("'", "''");

        int dola=0;
        try{
            Date dd = txtDate.getDate();
            DateFormat format=new SimpleDateFormat("yyyy/MM/dd");
            DateNaissance = format.format(dd);
            dola=1;
        }
        catch(Exception ex){

            dola=0;
        }
        fonction=cmbFonction.getSelectedItem().toString();
        String sal=spnSalaire.getValue().toString();
        salaire=Integer.parseInt(sal);
     
        Statut=cmbSatut.getSelectedItem().toString();
         boolean verif=s.isValid(email);
   String veraf=verifsalaire(salaire);
        if(nom.isEmpty()||prenom.isEmpty()||adresse.isEmpty()||email.isEmpty()){
            JOptionPane.showMessageDialog(null,"Tous les champs doivent etres remplis","Erreur",JOptionPane.ERROR_MESSAGE);
        }else if(nom.length()<2||prenom.length()<2){
            JOptionPane.showMessageDialog(null,"les champs noms et prenoms ne doivent pas inferieur a un caractere","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        else if(nif.length()<12){
            JOptionPane.showMessageDialog(null,"Le Cin doit contenir 10 Chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
        }

        else if(telephone.length()<=14){
            JOptionPane.showMessageDialog(null,"Les Telephones doivent avoir plus de avoir 8 chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        else if(veraf!=null){
            JOptionPane.showMessageDialog(null,veraf,"Erreur",JOptionPane.ERROR_MESSAGE);
        }
        else if(dola==0){
            JOptionPane.showMessageDialog(null,"Mettre une date de naissance corecte","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        else if(verif==false){
                JOptionPane.showMessageDialog(null,"Cet Email n'est pas valide","Erreur",JOptionPane.ERROR_MESSAGE);
            }
         else    if(filenameImg==null||nameImg==null){
               JOptionPane.showMessageDialog(null,"Choisissez une Image","Erreur",JOptionPane.ERROR_MESSAGE);
           }
            else    if(filenamedoc==null||namedoc==null){
               JOptionPane.showMessageDialog(null,"Choisissez un document","Erreur",JOptionPane.ERROR_MESSAGE);
           }
        else{

            try {
                Context cont=new InitialContext();
                InterfaceEmployer mato=(InterfaceEmployer) cont.lookup(ser.getEmploye());
                String message=mato.EnregistrerEmployer(nom, prenom, sexe, nif, adresse, telephone, email, DateNaissance, Statut, fonction, salaire);
               TransfererFichier img=new TransfererFichier();
                 String fe = FilenameUtils.getExtension(filenameImg);
                 String Code="Img"+message+"."+fe;
          String url=   img.EnvoyerFichier(filenameImg, nameImg,Code);
          mato.ModifierUrlPhoto(message, url);
          TransfererFichier imgs=new TransfererFichier();
                 String fes = FilenameUtils.getExtension(filenamedoc);
                 String Codes="CV"+message+"."+fes;
          String urls=   imgs.EnvoyerFichier(filenamedoc, namedoc,Codes);
          mato.ModifierUrldoc(message, urls);
          JOptionPane.showMessageDialog(FenGestionEmployer.this,"Emplyoyer Embaucher Avec Succes");
          renitialiser();
            } catch (NamingException | RemoteException ex) {
                Logger.getLogger(FenGestionEmployer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnembaucherActionPerformed
void rechercher(String code){
     try {
         // TODO add your handling code here:
        
          if(code==null){
            JOptionPane.showMessageDialog(null,"Code Vide","Erreur",JOptionPane.ERROR_MESSAGE);
            
          }
          else{
         Context cont=new InitialContext();
         InterfaceEmployer mato=(InterfaceEmployer) cont.lookup(ser.getEmploye());
         ArrayList<String> FicheEmployer;
         FicheEmployer=mato.FicheEmployer(code);
         String Code2=FicheEmployer.get(0);
          if(Code2!=null){
            // JOptionPane.showMessageDialog(fenEmbaucherEmploye.this,"Li bon"); 
            txtnom.setText(FicheEmployer.get(1));
             txtPrenom.setText(FicheEmployer.get(2));
             cmbSexe.setSelectedItem(FicheEmployer.get(3));
             mskNif.setText(FicheEmployer.get(4));
             txtAdresse.setText(FicheEmployer.get(5));
             mskTelephone.setText(FicheEmployer.get(6));
       
             txtEmail.setText(FicheEmployer.get(7));
              String datee=FicheEmployer.get(8);
      
		Date date = new SimpleDateFormat("yyyy/MM/dd").parse(datee);
                txtDate.setDate(date);
             cmbSatut.setSelectedItem(FicheEmployer.get(9));
             cmbFonction.setSelectedItem(FicheEmployer.get(10));
             String coe=String.valueOf((FicheEmployer.get(11)));
              urlphoto=FicheEmployer.get(12);
              urldoc=FicheEmployer.get(13);
                
                
                if(urlphoto!=null){
                  TransfererFichier img=new TransfererFichier();
                  img.recevoirFichier(urlphoto);
                  afficherImage(urlphoto);
                  img.effacerFichierClient(urlphoto); 
                }
                
                  if(urldoc!=null){
                  TransfererFichier img=new TransfererFichier();
                  img.recevoirFichier(urldoc); 
                          btnopendoc.setVisible(true);
                }
              int coef=Integer.parseInt(coe);
            spnSalaire.setValue(coef);
             
               btnmodifier.setVisible(true);
               btnmodifimg.setVisible(true);
               btnmodifcv.setVisible(true);
            
          }
          else{
                    JOptionPane.showMessageDialog(null,"Le code est incorect","Erreur",JOptionPane.ERROR_MESSAGE); 
                    btnmodifier.setVisible(false);
                    btnmodifimg.setVisible(false);
                    btnmodifcv.setVisible(false);
                            btnopendoc.setVisible(false);
                    renitialiser();
          }
          }
     } catch (NamingException | RemoteException | ParseException ex) {
         Logger.getLogger(FenGestionEmployer.class.getName()).log(Level.SEVERE, null, ex);
     }
}
    private void btnrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherActionPerformed
        try{
        code=JOptionPane.showInputDialog(FenGestionEmployer.this,"Veuillez Entrer le code").trim();
        }
        catch(Exception ff){
        code=null;
        }
        
        rechercher(code);
    }//GEN-LAST:event_btnrechercherActionPerformed
final void afficherImage(String urlphoto){
ImageIcon  icon=new ImageIcon(urlphoto);
      Image image=icon.getImage().getScaledInstance(259, 259, Image.SCALE_SMOOTH);
      icon = new ImageIcon(image);
       lblimage.setIcon(icon);
}
    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        // TODO add your handling code here:
        String nom,prenom,adresse,telephone,email,Statut;
        int salaire;
        nom=txtnom.getText().trim().replace("'", "''");
        prenom=txtPrenom.getText().trim().replace("'", "''");

        adresse=txtAdresse.getText().trim().replace("'", "''");
        telephone=mskTelephone.getText().trim();
        email=txtEmail.getText().trim().replace("'", "''");

        String sal=spnSalaire.getValue().toString();
        salaire=Integer.parseInt(sal);
        Statut=cmbSatut.getSelectedItem().toString();
 boolean verif=s.isValid(email);
   String veraf=verifsalaire(salaire);
        if(nom.isEmpty()||prenom.isEmpty()||adresse.isEmpty()||email.isEmpty()){
            JOptionPane.showMessageDialog(null,"Tous les champs doivent etres remplis","Erreur",JOptionPane.ERROR_MESSAGE);
        }else if(nom.length()<2||prenom.length()<2){
            JOptionPane.showMessageDialog(null,"les champs noms et prenoms ne doivent pas inferieur a un caractere","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        

        else if(telephone.length()<13){
            JOptionPane.showMessageDialog(null,"Les Telephones doivent avoir plus de avoir 8 chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        
         else if(veraf!=null){
            JOptionPane.showMessageDialog(null,veraf,"Erreur",JOptionPane.ERROR_MESSAGE);
        }
        
        else if(verif==false){
                JOptionPane.showMessageDialog(null,"Cet Email n'est pas valide","Erreur",JOptionPane.ERROR_MESSAGE);
            }

        else{

            try {
                Context cont=new InitialContext();
                InterfaceEmployer mato=(InterfaceEmployer) cont.lookup(ser.getEmploye());
                String message=mato.ModifierEmployer(nom, prenom, telephone, email, adresse, Statut, salaire, code);
                JOptionPane.showMessageDialog(FenGestionEmployer.this,message);
                renitialiser();
            } catch (NamingException ex) {
                Logger.getLogger(FenGestionEmployer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(FenGestionEmployer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnmodifierActionPerformed

    private void rdbenregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbenregActionPerformed
        // TODO add your handling code here:
        if(!rdbenreg.isSelected()){
            btnembaucher.setVisible(false);
            btnrechercher.setVisible(true);
            btnmodifier.setVisible(false);
            rdbrech.setSelected(true);
              btnupload.setVisible(false);
              btnuploadDoc.setVisible(false);
              btnmodifcv.setVisible(false);
                 btnmodifimg.setVisible(false);
            renitialiser();
                 btnopendoc.setVisible(false);
        }
        else{
            rdbrech.setSelected(false);
            btnembaucher.setVisible(true);
            btnupload.setVisible(true);
              btnuploadDoc.setVisible(true);
            btnrechercher.setVisible(false);
            btnmodifier.setVisible(false);
            btnmodifcv.setVisible(false);
                 btnmodifimg.setVisible(false);
            renitialiser();
                 btnopendoc.setVisible(false);
        }

    }//GEN-LAST:event_rdbenregActionPerformed

    private void rdbrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbrechActionPerformed
        // TODO add your handling code here:
             if(!rdbrech.isSelected()){
         btnembaucher.setVisible(true);
         btnrechercher.setVisible(false);
         btnmodifier.setVisible(false);
         rdbenreg.setSelected(true);
         btnupload.setVisible(true);
          btnuploadDoc.setVisible(true);
        btnmodifimg.setVisible(false);
             btnopendoc.setVisible(false);
             btnmodifcv.setVisible(false);
                 btnmodifimg.setVisible(false);
              renitialiser();
        }
        else{
        rdbenreg.setSelected(false);
        btnembaucher.setVisible(false);
        btnrechercher.setVisible(true);
        btnmodifier.setVisible(false);
        btnupload.setVisible(false);
        btnmodifimg.setVisible(false);
             btnopendoc.setVisible(false);
             btnmodifcv.setVisible(false);
                 btnmodifimg.setVisible(false);
                  btnuploadDoc.setVisible(false);
             renitialiser();
        }
    }//GEN-LAST:event_rdbrechActionPerformed

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        // TODO add your handling code here:
          JFileChooser chooser=new JFileChooser();
         chooser.addChoosableFileFilter(new ImageFilterJava());
            chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();
          
             filenameImg=f.getAbsolutePath();
              nameImg=f.getName();
            
           
                   afficherImage(filenameImg);
        }
        catch(Exception e){
          filenameImg=null;
          nameImg=null;
      afficherImage(Images);
     
        }
    }//GEN-LAST:event_btnuploadActionPerformed

    private void btnmodifimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifimgActionPerformed
        // TODO add your handling code here:
          int var=0;
        JFileChooser chooser=new JFileChooser();
         chooser.addChoosableFileFilter(new ImageFilterJava());
            chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();

             filenameImg=f.getAbsolutePath();
             nameImg=f.getName();
            
  afficherImage(filenameImg);
            var=1;
        }
        catch(Exception e){
       filenameImg=null;
       nameImg=null;
      afficherImage(Images);
            var=0;
        }
        if(var==1){
            
            TransfererFichier img=new TransfererFichier();
          
            img.effacerFichierServer(urlphoto);
              String fe = FilenameUtils.getExtension(filenameImg);
                 String Code="Img"+code+"."+fe;
            String url=   img.EnvoyerFichier(filenameImg, nameImg,Code);
            try {
        
                Context cont=new InitialContext();
                InterfaceEmployer mato=(InterfaceEmployer) cont.lookup(ser.getEmploye());
                mato.ModifierUrlPhoto(code, url);
                JOptionPane.showMessageDialog(FenGestionEmployer.this,"Image Modifier Avec Succes");
                rechercher(code);
             
            }

            catch (NamingException | RemoteException ex) {
                Logger.getLogger(FenEnregisterEtudiants.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnmodifimgActionPerformed

    private void btnuploadDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadDocActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser=new JFileChooser();
         chooser.addChoosableFileFilter(new DocFilterJava());
            chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();
          
             filenamedoc=f.getAbsolutePath();
              namedoc=f.getName();
            
          
        }
        catch(Exception e){
         filenamedoc=null;
         namedoc=null;
        }
    }//GEN-LAST:event_btnuploadDocActionPerformed

    private void btnmodifcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifcvActionPerformed
        // TODO add your handling code here:
             int var=0;
        JFileChooser chooser=new JFileChooser();
         chooser.addChoosableFileFilter(new DocFilterJava());
            chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();

             filenamedoc=f.getAbsolutePath();
              namedoc=f.getName();
        
            var=1;
        }
        catch(Exception e){
         filenamedoc=null;
         namedoc=null;
          
            var=0;
        }
        if(var==1){
        
            TransfererFichier img=new TransfererFichier();
          
            img.effacerFichierServer(urldoc);
              String fe = FilenameUtils.getExtension(filenamedoc);
                 String Code="Cv"+code+"."+fe;
            String url=   img.EnvoyerFichier(filenamedoc, namedoc,Code);
            try {
        
                Context cont=new InitialContext();
                InterfaceEmployer mato=(InterfaceEmployer) cont.lookup(ser.getEmploye());
                mato.ModifierUrldoc(code, url);
                JOptionPane.showMessageDialog(FenGestionEmployer.this,"Document Modifier Avec Succes");
                rechercher(code);
             
            }

            catch (NamingException | RemoteException ex) {
                Logger.getLogger(FenEnregisterEtudiants.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnmodifcvActionPerformed

    private void btnopendocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopendocActionPerformed
        // TODO add your handling code here:
        ServiceInterNet sa=new ServiceInterNet();
        sa.OpenNavigator(urldoc);
    }//GEN-LAST:event_btnopendocActionPerformed

    private void txtnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyTyped
        // TODO add your handling code here:
        co.isletter(evt);
    }//GEN-LAST:event_txtnomKeyTyped

    private void txtPrenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrenomKeyTyped
        // TODO add your handling code here:
        co.isletter(evt);
    }//GEN-LAST:event_txtPrenomKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salaire;
    private javax.swing.JButton btnembaucher;
    private javax.swing.JButton btnmodifcv;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnmodifimg;
    private javax.swing.JButton btnopendoc;
    private javax.swing.JButton btnrechercher;
    private javax.swing.JButton btnupload;
    private javax.swing.JButton btnuploadDoc;
    private javax.swing.JComboBox cmbFonction;
    private javax.swing.JComboBox cmbSatut;
    private javax.swing.JComboBox cmbSexe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblimage;
    private javax.swing.JFormattedTextField mskNif;
    private javax.swing.JFormattedTextField mskTelephone;
    private javax.swing.JRadioButton rdbenreg;
    private javax.swing.JRadioButton rdbrech;
    private javax.swing.JSpinner spnSalaire;
    private javax.swing.JTextField txtAdresse;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
