/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uni.intense.vue;


import com.uni.intense.presentation.InterfacePaiement;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ServiceReseau;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kelly
 */
public class FenListerTransactions extends javax.swing.JInternalFrame {
ServiceReseau ser=new ServiceReseau();
Contrainte co=new Contrainte();

    /**
     * Creates new form FenListerModalitePaiement
     */
    public FenListerTransactions() {
    try {
        initComponents();
        lister();
    } catch (NamingException ex) {
        Logger.getLogger(FenListerTransactions.class.getName()).log(Level.SEVERE, null, ex);
    } catch (RemoteException ex) {
        Logger.getLogger(FenListerTransactions.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnactualiser1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        btnfiltre = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnactualiser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh-icon.png"))); // NOI18N
        btnactualiser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiser1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Options", "Frais d'inscriptions ", "Frais d'entre", "Frais de Session"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Code Etudiant");

        txtcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodeKeyTyped(evt);
            }
        });

        btnfiltre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnfiltre.setText("Filtrer");
        btnfiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltreActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Liste des transactions");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnfiltre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnactualiser1)
                .addGap(25, 25, 25))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnfiltre))
                    .addComponent(btnactualiser1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualiser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiser1ActionPerformed
        try {
            // TODO add your handling code here:
            lister();
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(FenListerTransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnactualiser1ActionPerformed

    private void btnfiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltreActionPerformed
    try {
        // TODO add your handling code here:
        String code=txtcode.getText().trim();
        if(!code.equals("")){
        listeretu(code);
        }
        else{
             JOptionPane.showMessageDialog(null,"Tous les champs doivent etres remplis","Erreur",JOptionPane.ERROR_MESSAGE);
        }
    } catch (NamingException ex) {
        Logger.getLogger(FenListerTransactions.class.getName()).log(Level.SEVERE, null, ex);
    } catch (RemoteException ex) {
        Logger.getLogger(FenListerTransactions.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnfiltreActionPerformed

    private void txtcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodeKeyTyped
co.isletterdigit(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeKeyTyped
 void lister() throws NamingException, RemoteException{
                
                   Context cont=new InitialContext();
            InterfacePaiement mato=(InterfacePaiement) cont.lookup(ser.getPaiement());
            String [][] maliste=mato.Listertransactions();
      
String[] titre= { "Code","Code Compte", "Montant","Date du depot"};



 DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
 TableRowSorter<TableModel>sorter = new TableRowSorter<>(model);
      jTable1.setRowSorter(sorter);
 }
 
  void listeretu(String code) throws NamingException, RemoteException{
                
                   Context cont=new InitialContext();
            InterfacePaiement mato=(InterfacePaiement) cont.lookup(ser.getPaiement());
            String [][] maliste=mato.ListertransactionsEtudiant(code);
      
String[] titre= { "Code","Code Compte", "Montant","Date du depot"};



 DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
 TableRowSorter<TableModel>sorter = new TableRowSorter<>(model);
      jTable1.setRowSorter(sorter);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiser1;
    private javax.swing.JButton btnfiltre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcode;
    // End of variables declaration//GEN-END:variables
}
