/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uni.intense.vue;



import com.uni.intense.service.TransfererFichier;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JOptionPane;




/**
 *
 * @author kelly
 */
public class FenMenuUniv extends javax.swing.JFrame {
       private final ImageIcon icon;
       public JMenu lblnom,lblprenom,lblfonction,lblimage;
       public JLabel lblphoto;
    
        String Images="src//Image//personne2.png";
       
    /**
     * Creates new form FenMenuUniv
     */
    public FenMenuUniv() {
         icon =new ImageIcon("src/image/icone.png");
        setIconImage(icon.getImage());
        initComponents();
        commence();
//        if("".equals(lblimage.getText())){
       //  afficherImage("src//resources//ImgLaKe-79109.jpeg");
//        }
      //  else{
        // afficherImage(lblimage.getText());
         
      //  }
       
    
 // "src//resources//ImgLaKe-79109.jpeg"
    }
   
    final void commence(){
           menuBar.add(Box.createHorizontalGlue());
          lblnom = new JMenu("Nom");
//      sourceMenu.setMnemonic(KeyEvent.VK_S);
      menuBar.add(lblnom);
       lblprenom = new JMenu("Prenom");
  lblphoto = new JLabel();
//      refactorMenu.setMnemonic(KeyEvent.VK_R);
      menuBar.add(lblprenom);
       lblfonction = new JMenu("Fonction");
//      navigateMenu.setMnemonic(KeyEvent.VK_A);
      menuBar.add(lblfonction);
       
      lblimage = new JMenu();
      
  
//      refactorMenu.setMnemonic(KeyEvent.VK_R);
      menuBar.add(lblimage);
      menuBar.revalidate();
           lblnom.setEnabled(false);
                lblprenom.setEnabled(false);
                     lblfonction.setEnabled(false);
        setExtendedState(MAXIMIZED_BOTH);
//        try{
//               TransfererFichier t=new TransfererFichier();
//      String [] td=  t.listFiles("src//resources");
//        for (String string : td) {
//            System.out.println(string +"\n");
//            t.effacerFichierClient("src//resources/"+string);
//        }
//        
//        }
//         catch(Exception e)
//    {
//        //TODO exception
//    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuconexion = new javax.swing.JMenu();
        smndeconnexion = new javax.swing.JMenuItem();
        MenuProfesseur = new javax.swing.JMenu();
        smnprofesseur = new javax.swing.JMenuItem();
        MenuEvaluation = new javax.swing.JMenu();
        smnevaluation = new javax.swing.JMenuItem();
        MenuEtudiant = new javax.swing.JMenu();
        smnInsEtudiant = new javax.swing.JMenuItem();
        smnrecheretudiant = new javax.swing.JMenuItem();
        smnlisteretudiant = new javax.swing.JMenuItem();
        MenuOptionsCours = new javax.swing.JMenu();
        smnoptionscours = new javax.swing.JMenuItem();
        MenuBulletin = new javax.swing.JMenu();
        smnbulletin = new javax.swing.JMenuItem();
        MenuPaiement = new javax.swing.JMenu();
        smnmodalitepaiement = new javax.swing.JMenuItem();
        smndepot = new javax.swing.JMenuItem();
        smnlistemodpaie = new javax.swing.JMenuItem();
        smnlisteancpaie = new javax.swing.JMenuItem();
        smnlistetransactions = new javax.swing.JMenuItem();
        MenuEmployer = new javax.swing.JMenu();
        smngestemployer = new javax.swing.JMenuItem();
        smnlisteemploye = new javax.swing.JMenuItem();
        MenuUtilisateur = new javax.swing.JMenu();
        smncreerutlisateur = new javax.swing.JMenuItem();
        smnrechutilisasteur = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jDesktopPane1);

        menuconexion.setText("Connexion");

        smndeconnexion.setText("Deconnexion");
        smndeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smndeconnexionActionPerformed(evt);
            }
        });
        menuconexion.add(smndeconnexion);

        menuBar.add(menuconexion);

        MenuProfesseur.setText("Professeur");
        MenuProfesseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProfesseurActionPerformed(evt);
            }
        });

        smnprofesseur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/applications.png"))); // NOI18N
        smnprofesseur.setText("Gestion Professeur");
        smnprofesseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnprofesseurActionPerformed(evt);
            }
        });
        MenuProfesseur.add(smnprofesseur);

        menuBar.add(MenuProfesseur);

        MenuEvaluation.setText("Evaluation");

        smnevaluation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/test.png"))); // NOI18N
        smnevaluation.setText("Evaluation");
        smnevaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnevaluationActionPerformed(evt);
            }
        });
        MenuEvaluation.add(smnevaluation);

        menuBar.add(MenuEvaluation);

        MenuEtudiant.setText("Etudiant");

        smnInsEtudiant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/student_registration_24px.png"))); // NOI18N
        smnInsEtudiant.setText("Inscrire Un Etudiant");
        smnInsEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnInsEtudiantActionPerformed(evt);
            }
        });
        MenuEtudiant.add(smnInsEtudiant);

        smnrecheretudiant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        smnrecheretudiant.setText("Rechercher Etudiant");
        smnrecheretudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnrecheretudiantActionPerformed(evt);
            }
        });
        MenuEtudiant.add(smnrecheretudiant);

        smnlisteretudiant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/liste.png"))); // NOI18N
        smnlisteretudiant.setText("Lister Etudiant");
        smnlisteretudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnlisteretudiantActionPerformed(evt);
            }
        });
        MenuEtudiant.add(smnlisteretudiant);

        menuBar.add(MenuEtudiant);

        MenuOptionsCours.setText("Options Et Cours");

        smnoptionscours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apprentissage-en-ligne.png"))); // NOI18N
        smnoptionscours.setText("Options Cours");
        smnoptionscours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnoptionscoursActionPerformed(evt);
            }
        });
        MenuOptionsCours.add(smnoptionscours);

        menuBar.add(MenuOptionsCours);

        MenuBulletin.setText("Bulletin");

        smnbulletin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bulletin-de-vote.png"))); // NOI18N
        smnbulletin.setText("Voir Bulletin");
        smnbulletin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnbulletinActionPerformed(evt);
            }
        });
        MenuBulletin.add(smnbulletin);

        menuBar.add(MenuBulletin);

        MenuPaiement.setText("Paiement");
        MenuPaiement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPaiementActionPerformed(evt);
            }
        });

        smnmodalitepaiement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/le-recu.png"))); // NOI18N
        smnmodalitepaiement.setText("Modalite Paiement");
        smnmodalitepaiement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnmodalitepaiementActionPerformed(evt);
            }
        });
        MenuPaiement.add(smnmodalitepaiement);

        smndepot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cheque-dargent-modifier.png"))); // NOI18N
        smndepot.setText("Depot");
        smndepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smndepotActionPerformed(evt);
            }
        });
        MenuPaiement.add(smndepot);

        smnlistemodpaie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/liste.png"))); // NOI18N
        smnlistemodpaie.setText("Liste des Modalite de Paiemnet");
        smnlistemodpaie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnlistemodpaieActionPerformed(evt);
            }
        });
        MenuPaiement.add(smnlistemodpaie);

        smnlisteancpaie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/liste.png"))); // NOI18N
        smnlisteancpaie.setText("Liste des Ancien Modalite");
        smnlisteancpaie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnlisteancpaieActionPerformed(evt);
            }
        });
        MenuPaiement.add(smnlisteancpaie);

        smnlistetransactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/liste.png"))); // NOI18N
        smnlistetransactions.setText("Lister Transactions");
        smnlistetransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnlistetransactionsActionPerformed(evt);
            }
        });
        MenuPaiement.add(smnlistetransactions);

        menuBar.add(MenuPaiement);

        MenuEmployer.setText("Employer");

        smngestemployer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/applications.png"))); // NOI18N
        smngestemployer.setText("Gestion des Employes");
        smngestemployer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smngestemployerActionPerformed(evt);
            }
        });
        MenuEmployer.add(smngestemployer);

        smnlisteemploye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/liste.png"))); // NOI18N
        smnlisteemploye.setText("Liste des Employe");
        smnlisteemploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnlisteemployeActionPerformed(evt);
            }
        });
        MenuEmployer.add(smnlisteemploye);

        menuBar.add(MenuEmployer);

        MenuUtilisateur.setText("Utilisateur");
        MenuUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUtilisateurActionPerformed(evt);
            }
        });

        smncreerutlisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ajout-dutilisateur.png"))); // NOI18N
        smncreerutlisateur.setText("Creer Utilisateur");
        smncreerutlisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smncreerutlisateurActionPerformed(evt);
            }
        });
        MenuUtilisateur.add(smncreerutlisateur);

        smnrechutilisasteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        smnrechutilisasteur.setText("Rechercher Utilisateur");
        smnrechutilisasteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnrechutilisasteurActionPerformed(evt);
            }
        });
        MenuUtilisateur.add(smnrechutilisasteur);

        menuBar.add(MenuUtilisateur);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnprofesseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnprofesseurActionPerformed

            // TODO add your handling code here:
            jDesktopPane1.removeAll();
             jDesktopPane1.repaint();
            FenProfesseur fe=new FenProfesseur();
            jDesktopPane1.add(fe).setVisible(true);
       
    }//GEN-LAST:event_smnprofesseurActionPerformed

    private void MenuProfesseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProfesseurActionPerformed

    }//GEN-LAST:event_MenuProfesseurActionPerformed

    private void smnevaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnevaluationActionPerformed
        // TODO add your handling code here:
                   
         jDesktopPane1.removeAll();
          jDesktopPane1.repaint();
        FenExamen fe=new FenExamen();
        jDesktopPane1.add(fe).setVisible(true);
  
    }//GEN-LAST:event_smnevaluationActionPerformed

    private void smnInsEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnInsEtudiantActionPerformed
       
               // TODO add your handling code here:
                    jDesktopPane1.removeAll();
                     jDesktopPane1.repaint();
               FenEnregisterEtudiants fe=new FenEnregisterEtudiants();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnInsEtudiantActionPerformed

    private void smnrecheretudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnrecheretudiantActionPerformed

            // TODO add your handling code here:
           jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
            FenRechercherEtudiants fe=new FenRechercherEtudiants();
            jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnrecheretudiantActionPerformed

    private void smnoptionscoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnoptionscoursActionPerformed
           
               // TODO add your handling code here:
               jDesktopPane1.removeAll();
                jDesktopPane1.repaint();
               FenOptions fe=new FenOptions();
               jDesktopPane1.add(fe).setVisible(true);
         
    }//GEN-LAST:event_smnoptionscoursActionPerformed

    private void smnbulletinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnbulletinActionPerformed
        // TODO add your handling code here:
    
               // TODO add your handling code here:
               jDesktopPane1.removeAll();
               jDesktopPane1.repaint();
               FenBulletin fe=new FenBulletin();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnbulletinActionPerformed

    private void smnmodalitepaiementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnmodalitepaiementActionPerformed
        // TODO add your handling code here:
               jDesktopPane1.removeAll();
                jDesktopPane1.repaint();
               FenModalitePaiiement fe=new FenModalitePaiiement();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnmodalitepaiementActionPerformed

    private void smndepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smndepotActionPerformed
        // TODO add your handling code here:
               jDesktopPane1.removeAll();
                jDesktopPane1.repaint();
               FenDepot fe=new FenDepot();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smndepotActionPerformed

    private void smnlistemodpaieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnlistemodpaieActionPerformed
        // TODO add your handling code here:
               jDesktopPane1.removeAll();
                jDesktopPane1.repaint();
               FenListerModalitePaiement fe=new FenListerModalitePaiement();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnlistemodpaieActionPerformed

    private void smnlisteancpaieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnlisteancpaieActionPerformed
        // TODO add your handling code here:
               jDesktopPane1.removeAll();
                jDesktopPane1.repaint();
               FenListerAncienModalite fe=new FenListerAncienModalite();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnlisteancpaieActionPerformed

    private void MenuPaiementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPaiementActionPerformed
        // TODO add your handling code here:
          jDesktopPane1.removeAll();
           jDesktopPane1.repaint();
               FenListerTransactions fe=new FenListerTransactions();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_MenuPaiementActionPerformed

    private void smnlistetransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnlistetransactionsActionPerformed
        // TODO add your handling code here:
          jDesktopPane1.removeAll();
           jDesktopPane1.repaint();
               FenListerTransactions fe=new FenListerTransactions();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnlistetransactionsActionPerformed

    private void smnlisteretudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnlisteretudiantActionPerformed
        // TODO add your handling code here:
         jDesktopPane1.removeAll();
          jDesktopPane1.repaint();
               FenlisterEtudiants fe=new FenlisterEtudiants();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnlisteretudiantActionPerformed

    private void smngestemployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smngestemployerActionPerformed
        // TODO add your handling code here:
               jDesktopPane1.removeAll();
                jDesktopPane1.repaint();
               FenGestionEmployer fe=new FenGestionEmployer();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smngestemployerActionPerformed

    private void smnlisteemployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnlisteemployeActionPerformed
         
               // TODO add your handling code here:
               jDesktopPane1.removeAll();
                jDesktopPane1.repaint();
               FenlisterEmployer fe=new FenlisterEmployer();
               jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnlisteemployeActionPerformed

    private void MenuUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUtilisateurActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_MenuUtilisateurActionPerformed
 
    private void smncreerutlisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smncreerutlisateurActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
         jDesktopPane1.repaint();
        fenCreerUtilisateur fe=new fenCreerUtilisateur();
        jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smncreerutlisateurActionPerformed

    private void smnrechutilisasteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnrechutilisasteurActionPerformed
        // TODO add your handling code here:
           jDesktopPane1.removeAll();
            jDesktopPane1.repaint();
        fenRechercherUtilisateur fe=new fenRechercherUtilisateur();
        jDesktopPane1.add(fe).setVisible(true);
    }//GEN-LAST:event_smnrechutilisasteurActionPerformed

    private void smndeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smndeconnexionActionPerformed
        // TODO add your handling code here:
        login l=new login();
        l.show();
         this.dispose();
    }//GEN-LAST:event_smndeconnexionActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenMenuUniv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenMenuUniv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenMenuUniv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenMenuUniv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FenMenuUniv().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuBulletin;
    public javax.swing.JMenu MenuEmployer;
    public javax.swing.JMenu MenuEtudiant;
    public javax.swing.JMenu MenuEvaluation;
    public javax.swing.JMenu MenuOptionsCours;
    public javax.swing.JMenu MenuPaiement;
    public javax.swing.JMenu MenuProfesseur;
    public javax.swing.JMenu MenuUtilisateur;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuconexion;
    public javax.swing.JMenuItem smnInsEtudiant;
    public javax.swing.JMenuItem smnbulletin;
    public javax.swing.JMenuItem smncreerutlisateur;
    private javax.swing.JMenuItem smndeconnexion;
    public javax.swing.JMenuItem smndepot;
    public javax.swing.JMenuItem smnevaluation;
    public javax.swing.JMenuItem smngestemployer;
    public javax.swing.JMenuItem smnlisteancpaie;
    public javax.swing.JMenuItem smnlisteemploye;
    public javax.swing.JMenuItem smnlistemodpaie;
    public javax.swing.JMenuItem smnlisteretudiant;
    public javax.swing.JMenuItem smnlistetransactions;
    public javax.swing.JMenuItem smnmodalitepaiement;
    public javax.swing.JMenuItem smnoptionscours;
    public javax.swing.JMenuItem smnprofesseur;
    public javax.swing.JMenuItem smnrecheretudiant;
    public javax.swing.JMenuItem smnrechutilisasteur;
    // End of variables declaration//GEN-END:variables
}
