/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uni.intense.vue;

import com.uni.intense.presentation.InterfaceEmployer;
import com.uni.intense.presentation.InterfacePaiement;
import com.uni.intense.presentation.InterfaceService;
import com.uni.intense.service.ServiceReseau;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

/**
 *
 * @author kelly
 */
public class FenModalitePaiiement extends javax.swing.JInternalFrame {
ServiceReseau ser=new ServiceReseau();

String Dateenreg;
    /**
     * Creates new form FenModalitePaiiement
     */
    public FenModalitePaiiement() {
    try {
        initComponents();
        rempliroption();
          rdbrech .setSelected(false);
         panenrg.setVisible(true);
panrech.setVisible(false);
 btnenreg.setVisible(true);
  btnmodif.setVisible(false);
    } catch (NamingException ex) {
        Logger.getLogger(FenModalitePaiiement.class.getName()).log(Level.SEVERE, null, ex);
    } catch (RemoteException ex) {
        Logger.getLogger(FenModalitePaiiement.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panenrg = new javax.swing.JPanel();
        txtinsc = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsess = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtentre = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxoptioncours = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        panrech = new javax.swing.JPanel();
        cbxoptioncours2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnrech1 = new javax.swing.JButton();
        rdbrech = new javax.swing.JRadioButton();
        rdbenreg = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnenreg = new javax.swing.JButton();
        btnmodif = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panenrg.setBackground(new java.awt.Color(255, 255, 255));
        panenrg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtinsc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panenrg.add(txtinsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 47, 146, -1));

        jLabel1.setText("Frais D'inscriptions");
        panenrg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel2.setText("Frais Session");
        panenrg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        txtsess.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panenrg.add(txtsess, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 87, 146, -1));

        jLabel3.setText("Frais D'Entre");
        panenrg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 50, -1, -1));

        txtentre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panenrg.add(txtentre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 47, 146, -1));

        jLabel6.setText("Options");
        panenrg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 90, -1, -1));

        cbxoptioncours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxoptioncoursActionPerformed(evt);
            }
        });
        panenrg.add(cbxoptioncours, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 87, 143, -1));

        getContentPane().add(panenrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 297, 636, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panrech.setBackground(new java.awt.Color(255, 255, 255));
        panrech.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxoptioncours2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxoptioncours2ActionPerformed(evt);
            }
        });
        panrech.add(cbxoptioncours2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 195, -1));

        jLabel4.setText("Options");
        panrech.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnrech1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnrech1.setText("Rechercher");
        btnrech1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrech1ActionPerformed(evt);
            }
        });
        panrech.add(btnrech1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jPanel1.add(panrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        rdbrech.setText("Rechercher");
        rdbrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbrechActionPerformed(evt);
            }
        });
        jPanel1.add(rdbrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        rdbenreg.setSelected(true);
        rdbenreg.setText("Enregistrement");
        rdbenreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbenregActionPerformed(evt);
            }
        });
        jPanel1.add(rdbenreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gestion de Modalites de Paiement");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel8)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(41, 41, 41))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        btnenreg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ajouter.png"))); // NOI18N
        btnenreg.setText("Enregistrer");
        btnenreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenregActionPerformed(evt);
            }
        });
        jPanel1.add(btnenreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        btnmodif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit-icon.png"))); // NOI18N
        btnmodif.setText("Mettre a Jour");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxoptioncours2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxoptioncours2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxoptioncours2ActionPerformed

    private void btnenregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenregActionPerformed
    try {
        // TODO add your handling code here:
        String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
        int dola=0;
        try{
             double fraisInscription=Double.parseDouble(txtinsc.getText().trim());
                        double fraisDentres=Double.parseDouble(txtentre.getText().trim());
                                double fraisSession=Double.parseDouble(txtsess.getText().trim());
                                
                                dola=1;
        }
              catch(Exception es){
              dola=0;
              }                  
        if(txtinsc.getText().trim().isEmpty()||txtentre.getText().trim().isEmpty()||txtsess.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(null,"Remplissez tous les Frais","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        else if(dola==0){
        JOptionPane.showMessageDialog(null,"Les Champs doivent avoir uniquement des chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        
        else{
        
             double fraisInscription=Double.parseDouble(txtinsc.getText().trim());
                        double fraisDentres=Double.parseDouble(txtentre.getText().trim());
                                double fraisSession=Double.parseDouble(txtsess.getText().trim());
                                
                                if(fraisInscription<30|| fraisDentres<30||fraisSession<30){
                             JOptionPane.showMessageDialog(null,"Les frais doivent etre superieur ou egale a 30","Erreur",JOptionPane.ERROR_MESSAGE);    
                                }
                                
                                else{
                                
                              
        Context cont=new InitialContext();
        InterfacePaiement mato=(InterfacePaiement) cont.lookup(ser.getPaiement());
        String message=mato.EnregistrerPaiement(Nom_Opt, fraisInscription, fraisDentres, fraisSession);
        JOptionPane.showMessageDialog(FenModalitePaiiement.this,message);
                                }
                                
      
        }
    } catch (NamingException ex) {
        Logger.getLogger(FenModalitePaiiement.class.getName()).log(Level.SEVERE, null, ex);
    } catch (RemoteException ex) {
        Logger.getLogger(FenModalitePaiiement.class.getName()).log(Level.SEVERE, null, ex);
    }
         
    }//GEN-LAST:event_btnenregActionPerformed

    private void btnrech1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrech1ActionPerformed
        // TODO add your handling code here:
         try {
        // TODO add your handling code here:
        String Nom_Opt=cbxoptioncours2.getSelectedItem().toString();
     
        Context cont=new InitialContext();
        InterfacePaiement mato=(InterfacePaiement) cont.lookup(ser.getPaiement());
        ArrayList Fiche=new ArrayList();
        Fiche=mato.FichePaiement2(Nom_Opt);
        String codepc2=Fiche.get(0).toString();
        if(codepc2==null){
        JOptionPane.showMessageDialog(null,"Le code Est incorrect","Erreur",JOptionPane.ERROR_MESSAGE);
         panenrg.setVisible(false);
  btnmodif.setVisible(false);
        }
        else {
              cbxoptioncours.setSelectedItem(Fiche.get(1).toString());
              txtinsc.setText(Fiche.get(2).toString());
              txtentre.setText(Fiche.get(3).toString());
              txtsess.setText(Fiche.get(4).toString());
               Dateenreg=Fiche.get(5).toString();
                panenrg.setVisible(true);
  btnmodif.setVisible(true);
           
        }
        
    } catch (NamingException ex) {
        Logger.getLogger(FenModalitePaiiement.class.getName()).log(Level.SEVERE, null, ex);
    } catch (RemoteException ex) {
        Logger.getLogger(FenModalitePaiiement.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnrech1ActionPerformed

    private void cbxoptioncoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxoptioncoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxoptioncoursActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
    try {
        // TODO add your handling code here:

        String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
  
        int dola=0;
        try{
             double fraisInscription=Double.parseDouble(txtinsc.getText().trim());
                        double fraisDentres=Double.parseDouble(txtentre.getText().trim());
                                double fraisSession=Double.parseDouble(txtsess.getText().trim());
                                
                                dola=1;
        }
              catch(Exception es){
              dola=0;
              }                  
        if(txtinsc.getText().trim().isEmpty()||txtentre.getText().trim().isEmpty()||txtsess.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(null,"Remplissez tous les Frais","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        else if(dola==0){
        JOptionPane.showMessageDialog(null,"Veuillez Remplir le format","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        
        else{
        
             double fraisInscription=Double.parseDouble(txtinsc.getText().trim());
                        double fraisDentres=Double.parseDouble(txtentre.getText().trim());
                                double fraisSession=Double.parseDouble(txtsess.getText().trim());
                                
                                if(fraisInscription<30|| fraisDentres<30||fraisSession<30){
                             JOptionPane.showMessageDialog(null,"Les frais doivent etre superieur ou egale a 30","Erreur",JOptionPane.ERROR_MESSAGE);    
                                }
                                
                                else{
                                
                                       
        Context cont=new InitialContext();
        InterfacePaiement mato=(InterfacePaiement) cont.lookup(ser.getPaiement());
              String message=mato.ModifierPaiement( Nom_Opt, Dateenreg, fraisInscription, fraisDentres, fraisSession);
        JOptionPane.showMessageDialog(FenModalitePaiiement.this,message);
                                }
        

        }
    } catch (NamingException ex) {
        Logger.getLogger(FenModalitePaiiement.class.getName()).log(Level.SEVERE, null, ex);
    } catch (RemoteException ex) {
        Logger.getLogger(FenModalitePaiiement.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnmodifActionPerformed

    private void rdbenregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbenregActionPerformed
        // TODO add your handling code here:
         if(!rdbenreg.isSelected()){
        panenrg.setVisible(false);
panrech.setVisible(true);
 rdbrech .setSelected(true);
 btnenreg.setVisible(false);
  btnmodif.setVisible(false);
        }
         
         else{
         rdbrech .setSelected(false);
         panenrg.setVisible(true);
panrech.setVisible(false);
 btnenreg.setVisible(true);
  btnmodif.setVisible(false);
         }
    }//GEN-LAST:event_rdbenregActionPerformed

    private void rdbrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbrechActionPerformed
        // TODO add your handling code here:
                 if(!rdbrech.isSelected()){
        panrech.setVisible(false);
panenrg.setVisible(true);
 rdbenreg .setSelected(true);
 btnenreg.setVisible(true);
  btnmodif.setVisible(false);
        }
         
         else{
         rdbenreg .setSelected(false);
         panenrg.setVisible(false);
panrech.setVisible(true);
 btnenreg.setVisible(false);
  btnmodif.setVisible(false);
         }
    }//GEN-LAST:event_rdbrechActionPerformed

void rempliroption() throws NamingException, RemoteException{
    
                    ArrayList<String> Al=new ArrayList<>();
                    Context cont=new InitialContext();
                  InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
                    Al=  mato.remplirComboOptions();
                     int i=0;
                     cbxoptioncours2.removeAllItems();
                     cbxoptioncours.removeAllItems();
        for(String dep:Al)
        {
           
            cbxoptioncours2.addItem(dep);
             cbxoptioncours.addItem(dep);
            i++;
        } 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenreg;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnrech1;
    private javax.swing.JComboBox<String> cbxoptioncours;
    private javax.swing.JComboBox<String> cbxoptioncours2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panenrg;
    private javax.swing.JPanel panrech;
    private javax.swing.JRadioButton rdbenreg;
    private javax.swing.JRadioButton rdbrech;
    private javax.swing.JFormattedTextField txtentre;
    private javax.swing.JFormattedTextField txtinsc;
    private javax.swing.JFormattedTextField txtsess;
    // End of variables declaration//GEN-END:variables
}
