/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uni.intense.vue;

import com.uni.intense.presentation.IEtudiants;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ImageFilterJava;
import com.uni.intense.service.ServiceInterNet;
import com.uni.intense.service.ServiceReseau;
import com.uni.intense.service.TransfererFichier;
import java.awt.Image;
import java.io.File;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author kelly
 */
public class FenRechercherEtudiants extends javax.swing.JInternalFrame {
private String CodeEtud;
    private String filename;
      private String filename1;
      private String urlphoto;
      String Images="src//Image//personne2.png";
ServiceReseau ser=new ServiceReseau();

ServiceInterNet s=new ServiceInterNet();
Contrainte co=new Contrainte();
    /**
     * Creates new form FenRechercherEtudiants2
     */
    public FenRechercherEtudiants() {
        initComponents();
        PanGlobalEtud.setVisible(false);
        afficherImage(".//ressource//personne2.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanGlobalEtud = new javax.swing.JPanel();
        txtNif = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodOpt = new javax.swing.JTextField();
        txtVacation = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtCodeEtud = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbSexe = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNomRespon = new javax.swing.JTextField();
        txtPhoneRespon = new javax.swing.JFormattedTextField();
        bntModifierEtu = new javax.swing.JButton();
        txtPhone = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtpromo = new javax.swing.JTextField();
        txtniv = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnreinscrire = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        btnmodifimg = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtCodeEt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanGlobalEtud.setBackground(new java.awt.Color(255, 255, 255));
        PanGlobalEtud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNif.setEnabled(false);
        PanGlobalEtud.add(txtNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 159, 144, -1));

        jLabel15.setText("Option");
        PanGlobalEtud.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 236, -1, -1));

        jLabel14.setText("Vacation");
        PanGlobalEtud.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 193, -1, -1));

        txtCodOpt.setEnabled(false);
        PanGlobalEtud.add(txtCodOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 233, 143, -1));

        txtVacation.setEnabled(false);
        PanGlobalEtud.add(txtVacation, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 193, 144, -1));

        txtDate.setEnabled(false);
        PanGlobalEtud.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 125, 144, -1));

        txtCodeEtud.setBackground(new java.awt.Color(240, 240, 240));
        txtCodeEtud.setEnabled(false);
        txtCodeEtud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeEtudActionPerformed(evt);
            }
        });
        PanGlobalEtud.add(txtCodeEtud, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 57, 161, -1));

        jLabel4.setText("Sexe");
        PanGlobalEtud.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 97, -1, -1));

        cmbSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculin", "Feminin" }));
        cmbSexe.setEnabled(false);
        PanGlobalEtud.add(cmbSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 97, 151, -1));

        jLabel13.setText("Nif / Cin");
        PanGlobalEtud.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 162, -1, -1));

        jLabel5.setText("Date Naissance");
        PanGlobalEtud.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 128, -1, -1));

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Adresse");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, -1, -1));
        jPanel1.add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 101, 158, -1));

        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 135, 158, -1));

        jLabel8.setText("Phone");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, -1, -1));

        jLabel9.setText("Nom Responsable ");

        jLabel10.setText("Phone Responsable");

        txtNomRespon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomResponKeyTyped(evt);
            }
        });

        try {
            txtPhoneRespon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+509 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomRespon, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhoneRespon)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNomRespon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPhoneRespon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 109, -1, -1));

        bntModifierEtu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit-icon.png"))); // NOI18N
        bntModifierEtu.setText("Modifier");
        bntModifierEtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModifierEtuActionPerformed(evt);
            }
        });
        jPanel1.add(bntModifierEtu, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 209, -1, -1));

        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+509####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 169, 158, -1));

        jLabel2.setText("Nom");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, -1, -1));

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomKeyTyped(evt);
            }
        });
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 40, 158, -1));

        txtPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrenomKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 40, 161, -1));

        jLabel3.setText("Prenom");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 43, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Les Donnée modifiables");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 17, -1, -1));

        PanGlobalEtud.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 44, -1, -1));

        jLabel16.setText("promotion");
        PanGlobalEtud.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 270, -1, -1));

        txtpromo.setEnabled(false);
        PanGlobalEtud.add(txtpromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 267, 143, -1));

        txtniv.setEnabled(false);
        PanGlobalEtud.add(txtniv, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 301, 143, -1));

        jLabel17.setText("Niveau Actuelle");
        PanGlobalEtud.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 304, -1, -1));

        btnreinscrire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit-icon.png"))); // NOI18N
        btnreinscrire.setText("Reinscire");
        btnreinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreinscrireActionPerformed(evt);
            }
        });
        PanGlobalEtud.add(btnreinscrire, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 354, -1, -1));
        PanGlobalEtud.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 44, 259, 259));

        btnmodifimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Camera-icon.png"))); // NOI18N
        btnmodifimg.setText("Modifier l'image");
        btnmodifimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifimgActionPerformed(evt);
            }
        });
        PanGlobalEtud.add(btnmodifimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 338, -1, -1));

        getContentPane().add(PanGlobalEtud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, -1, 380));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, -1, -1));

        txtCodeEt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodeEtKeyTyped(evt);
            }
        });
        jPanel4.add(txtCodeEt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 161, -1));

        jLabel1.setText("Code Etudiant");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 91, 20));

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Informations Etudiant");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel18)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 70));

        jPanel5.setBackground(new java.awt.Color(25, 118, 211));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1290, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
final void afficherImage(String urlphoto){
ImageIcon  icon=new ImageIcon(urlphoto);
      Image image=icon.getImage().getScaledInstance(259, 259, Image.SCALE_SMOOTH);
      icon = new ImageIcon(image);
       lblimage.setIcon(icon);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String CodeEt=txtCodeEt.getText().trim();
        if(CodeEt.isEmpty()){
            JOptionPane.showMessageDialog(null,"Entrez le code","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        else{
            rechercher(CodeEt);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodeEtudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeEtudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeEtudActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed
void rechercher( String CodeEt){
try {
         
            // TODO add your handling code here:
 
        
            Context cont=new InitialContext();
            IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
             ArrayList<String> Fiche;
             Fiche=mato.FicheEtudiant(CodeEt);
             CodeEtud=Fiche.get(0);
             if(CodeEt.equals(CodeEtud)){
                
               
                txtCodeEtud.setText(Fiche.get(0));
                txtNom.setText(Fiche.get(1));
                txtPrenom.setText(Fiche.get(2));
                cmbSexe.setSelectedItem(Fiche.get(3));
                txtDate.setText(Fiche.get(4));               
                txtNif.setText(Fiche.get(5));                
                txtAdresse.setText(Fiche.get(6));
                txtEmail.setText(Fiche.get(7));
                txtPhone.setText(Fiche.get(8));
                txtNomRespon.setText(Fiche.get(9));
                txtPhoneRespon.setText(Fiche.get(10));
                txtVacation.setText(Fiche.get(11));
                txtCodOpt.setText(Fiche.get(12));
                txtpromo.setText(Fiche.get(13));
                txtniv.setText(Fiche.get(14));
                urlphoto=Fiche.get(15);
             
                
                if(urlphoto!=null){
                  TransfererFichier img=new TransfererFichier();
                  img.recevoirFichier(urlphoto);
                  afficherImage(urlphoto);
                  img.effacerFichierClient(urlphoto); 
                }
                else{
                 afficherImage(Images);
                }
                
                 PanGlobalEtud.setVisible(true);
                 bntModifierEtu.setVisible(true);
             }
             else{
                   PanGlobalEtud.setVisible(false);
         JOptionPane.showMessageDialog(null," le code de l'etudiant est Incorect","Erreur",JOptionPane.ERROR_MESSAGE);
            
             }
        }catch (NamingException ex) {
           Logger.getLogger(FenEnregisterEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(FenRechercherEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        } 

}
    private void bntModifierEtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModifierEtuActionPerformed
        // TODO add your handling code here:
        try {
         
            // TODO add your handling code here:
            String CodeEtud=txtCodeEtud.getText();
            if(CodeEtud.isEmpty()){
                JOptionPane.showMessageDialog(null,"Entrer le code de l'etudiant","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else{

                String Nom=txtNom.getText().trim().replace("'", "''");
                String Prenom =txtPrenom.getText().trim().replace("'", "''");

                String Adresse =txtAdresse.getText().trim().replace("'", "''");
                String Email =txtEmail.getText().trim().replace("'", "''");
                String Phone =txtPhone.getText();
                String NomResponsable =txtNomRespon.getText().trim().replace("'", "''");
                String PhoneResponsable =txtPhoneRespon.getText();
   boolean verif=s.isValid(Email);
                if(Nom.isEmpty()||Prenom.isEmpty()||Adresse.isEmpty()||Email.isEmpty()||NomResponsable.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Tous les champs doivent etres remplis","Erreur",JOptionPane.ERROR_MESSAGE);
                }else if(Nom.length()<2||Prenom.length()<2||NomResponsable.length()<2){
                    JOptionPane.showMessageDialog(null,"les champs noms et prenoms et Nom des responsable ne doivent pas inferieur a un caractere","Erreur",JOptionPane.ERROR_MESSAGE);
                }
                else if(Phone.length()<13||PhoneResponsable.length()<13){
                JOptionPane.showMessageDialog(null,"Les Telephones doivent avoir plus de avoir 8 chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
            }
                 else if(verif==false){
                JOptionPane.showMessageDialog(null,"Cet Email n'est pas valide","Erreur",JOptionPane.ERROR_MESSAGE);
            }
                else{
                    Context cont=new InitialContext();
                    IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
                    String gu= mato.ModifierEtudiant(CodeEtud, Nom, Prenom, Adresse, Email, Phone, NomResponsable, PhoneResponsable);
                    JOptionPane.showMessageDialog(FenRechercherEtudiants.this,gu);
                    rechercher(CodeEtud);
                }
            }
        }catch (NamingException ex) {
            Logger.getLogger(FenEnregisterEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(FenRechercherEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntModifierEtuActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void btnreinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreinscrireActionPerformed
        try {
            // TODO add your handling code here:
        
            String CodeEtud=txtCodeEtud.getText().trim();
            String niveau=txtniv.getText().trim();
            Context cont=new InitialContext();
            IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
            String gu= mato.ReinscrireEtud(niveau, CodeEtud);
            JOptionPane.showMessageDialog(FenRechercherEtudiants.this,gu);
            rechercher(CodeEtud);
        } catch (NamingException ex) {
            Logger.getLogger(FenRechercherEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(FenRechercherEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnreinscrireActionPerformed

    private void btnmodifimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifimgActionPerformed
        // TODO add your handling code here:
        String code=txtCodeEtud.getText();
        int var=0;
        JFileChooser chooser=new JFileChooser();
         chooser.addChoosableFileFilter(new ImageFilterJava());
            chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();

             filename=f.getAbsolutePath();
            filename1=f.getName();
         
            afficherImage(filename);
            var=1;
                }
                catch(Exception e){
                
                    afficherImage(Images);
                   var=0;
                }
        if(var==1){
      
          TransfererFichier img=new TransfererFichier();
          if(urlphoto!=null){
           img.effacerFichierServer(urlphoto);
          }
        
           String fe = FilenameUtils.getExtension(filename);
                 String Code="Img"+code+"."+fe;
          String url=   img.EnvoyerFichier(filename, filename1,Code);

          try {
   
          Context cont=new InitialContext();
            IEtudiants mato=(IEtudiants) cont.lookup(ser.getEtudiant());
          mato.ModifierUrlPhoto(code, url);
             JOptionPane.showMessageDialog(FenRechercherEtudiants.this,"Image Modifier Avec Succes");
              rechercher(code);
          }
          
          catch (NamingException | RemoteException ex) {
           Logger.getLogger(FenEnregisterEtudiants.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnmodifimgActionPerformed

    private void txtCodeEtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeEtKeyTyped
        // TODO add your handling code here:
        co.isletterdigit(evt);
    }//GEN-LAST:event_txtCodeEtKeyTyped

    private void txtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyTyped
        // TODO add your handling code here:
         co.isletter(evt);
    }//GEN-LAST:event_txtNomKeyTyped

    private void txtPrenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrenomKeyTyped
        // TODO add your handling code here:
         co.isletter(evt);
    }//GEN-LAST:event_txtPrenomKeyTyped

    private void txtNomResponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomResponKeyTyped
        // TODO add your handling code here:
         co.isletter(evt);
    }//GEN-LAST:event_txtNomResponKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanGlobalEtud;
    private javax.swing.JButton bntModifierEtu;
    private javax.swing.JButton btnmodifimg;
    private javax.swing.JButton btnreinscrire;
    private javax.swing.JComboBox<String> cmbSexe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblimage;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCodOpt;
    private javax.swing.JTextField txtCodeEt;
    private javax.swing.JTextField txtCodeEtud;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNomRespon;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JFormattedTextField txtPhoneRespon;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtVacation;
    private javax.swing.JTextField txtniv;
    private javax.swing.JTextField txtpromo;
    // End of variables declaration//GEN-END:variables
}
