/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uni.intense.vue;

import com.uni.intense.presentation.InterfaceEmployer;
import com.uni.intense.presentation.InterfaceUtilisateur;
import com.uni.intense.service.ServiceInterNet;
import com.uni.intense.service.ServiceReseau;
import com.uni.intense.service.TransfererFichier;
import java.awt.Image;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ME1
 */
public class login extends javax.swing.JFrame {
   ServiceReseau ser=new ServiceReseau();
     ServiceInterNet s=new ServiceInterNet();
   
 Boolean isIt = false;
   int  counter;

public static  String nomUser,Motpasse,fonction,nom,prenom,statut;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        txtNomUser.setBackground(new java.awt.Color(0,0,0,1));
        txtMotPasse.setBackground(new java.awt.Color(0,0,0,1));
        
       jPanel4.setVisible(false);
        
        
    }
void timer (){
    
    btnlogin.setVisible(false);
    lblforgot.setVisible(false);
    lblhello.setVisible(false);
    lblmot.setVisible(false);
    lblpass.setVisible(false);
      
       lblpseudo.setVisible(false);
    lbltxtuser.setVisible(false);
    txtMotPasse.setVisible(false);
      txtNomUser.setVisible(false);
        jPanel4.setVisible(true);
  java.util.Timer timer = new java.util.Timer();
        
   
        
       TimerTask task = new TimerTask(){
       public void run(){
           tm.setText(Integer.toString(counter));
           sec.setText("Secondes");
           counter --;
           if(counter == 0){
              sec.setText("Seconde");
           }else if(counter == -1){
                timer.cancel();
                
              sec.setText("Seconde");
               jPanel4.setVisible(false);
                 btnlogin.setVisible(true);
    lblforgot.setVisible(true);
    lblhello.setVisible(true);
    lblmot.setVisible(true);
    lblpass.setVisible(true);
      
       lblpseudo.setVisible(true);
    lbltxtuser.setVisible(true);
    txtMotPasse.setVisible(true);
      txtNomUser.setVisible(true);
           }else if(isIt){
               timer.cancel();
              
               isIt = false;
           }
         }
       };
        timer.scheduleAtFixedRate(task, 1000, 1000);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblhello = new javax.swing.JLabel();
        lblpseudo = new javax.swing.JLabel();
        txtNomUser = new javax.swing.JTextField();
        lbltxtuser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        txtMotPasse = new javax.swing.JPasswordField();
        lblmot = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        lblforgot = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tm = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 118, 211));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Universite INTENSE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 500, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg-login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 500, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 29));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Connexion");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 420, 41));

        lblhello.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblhello.setForeground(new java.awt.Color(255, 255, 255));
        lblhello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhello.setText("Hello! Let's get started");
        jPanel2.add(lblhello, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 420, -1));

        lblpseudo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblpseudo.setForeground(new java.awt.Color(199, 226, 255));
        lblpseudo.setText("Pseudo");
        jPanel2.add(lblpseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 123, 341, -1));

        txtNomUser.setFont(txtNomUser.getFont().deriveFont(txtNomUser.getFont().getSize()+2f));
        txtNomUser.setForeground(new java.awt.Color(255, 255, 255));
        txtNomUser.setBorder(null);
        jPanel2.add(txtNomUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 140, 240, 30));

        lbltxtuser.setForeground(new java.awt.Color(255, 255, 255));
        lbltxtuser.setText("_________________________________________");
        jPanel2.add(lbltxtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 147, 290, 39));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_20px_1.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 147, 40, 39));

        lblpass.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblpass.setForeground(new java.awt.Color(199, 226, 255));
        lblpass.setText("Mot de Passe");
        jPanel2.add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 192, 341, -1));

        txtMotPasse.setFont(txtMotPasse.getFont().deriveFont(txtMotPasse.getFont().getSize()+2f));
        txtMotPasse.setForeground(new java.awt.Color(255, 255, 255));
        txtMotPasse.setBorder(null);
        txtMotPasse.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtMotPasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 30));

        lblmot.setForeground(new java.awt.Color(255, 255, 255));
        lblmot.setText("_________________________________________");
        jPanel2.add(lblmot, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 216, 290, 40));

        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_invisible_20px_1.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel2.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 216, 40, 40));

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_eye_20px_1.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 216, 40, 40));

        lblforgot.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblforgot.setForeground(new java.awt.Color(199, 226, 255));
        lblforgot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblforgot.setText("Forget Password?");
        lblforgot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(lblforgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 261, 121, 27));

        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(25, 118, 211));
        btnlogin.setText("LOGIN");
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 306, 341, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sign Up");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 357, 122, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(199, 226, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Don't have an account?");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 357, 213, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel4PropertyChange(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Veuillez patienter");

        tm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        sec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(tm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(tm)
                .addGap(18, 18, 18)
                .addComponent(sec)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 420, 440));

        setSize(new java.awt.Dimension(916, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        txtMotPasse.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        txtMotPasse.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
          try {
             // TODO add your handling code here:
             // reception information
           String   nomUsers=txtNomUser.getText().trim();
             char[] motpasse=txtMotPasse.getPassword();
             String motepasse2=String.valueOf(motpasse);
             
             // verification informations vide
             if(nomUsers.isEmpty() || motepasse2.isEmpty()){
               JOptionPane.showMessageDialog(null,"Tous les champs doivent etres remplis","Erreur",JOptionPane.ERROR_MESSAGE);
             }
         //else verification info vide  
             else{
             
             
        // connexion client serveur
             Context cont=new InitialContext();
         
             InterfaceUtilisateur mato=(InterfaceUtilisateur) cont.lookup(ser.getUtilisateur());
             
             String nomUtil = mato.TesteUtilisateur(nomUsers);
             
              ArrayList<String> FicheLogin;
              FicheLogin=mato.FicheLogin(nomUsers, motepasse2);
              String code=FicheLogin.get(0);
              String etat=FicheLogin.get(3);
          
               // si non itilizate a epi mot passe la pa bon 
              if(nomUtil == null && code==null){
              JOptionPane.showMessageDialog(null,"Le Nom ou Mot de passe de cet Utilisateur est Incorrect","Erreur",JOptionPane.ERROR_MESSAGE); 
              }
              // si non itilizate a bon men mot passe la pa bon 
            else  if (nomUtil != null && code == null) 
                {
                    int etatU = mato.UtilisateurBloque(nomUsers);

                    // si moun nan inactif
                    if (etatU == 0)
                    {
                                 JOptionPane.showMessageDialog(null,"Utilisateur bloque","Erreur",JOptionPane.ERROR_MESSAGE);
                     
                    }
                    // sinon li pa inactif
                    else
                    {
                         mato.EnregistrerTantative(nomUsers);

                        int compterTantative = mato.CompterTantative(nomUsers);
                        int restant = 3 - compterTantative;
                        
                        // si moun nan  eseye konekte 3 fois 
                        switch (compterTantative) {
                            case 3:
                                {
                                   counter=5;
                                    timer();
                                    break;
                                }
                            case 4:
                                {
                                   counter=10;
                                    timer();
                                 
                                    break;
                                }
                            case 5:
                                {
                                    counter=15;
                                    timer();
                                    break;
                                }
                            case 6:
                                mato.BloqueUtilisateur(nomUsers);
                                String expediteur = "marcadieu14@gmail.com".trim();
                                String sujet="Tentative de connexion au systeme";
                                String Mes = "L'utilisateur " + nomUsers + " à tenter de connecter à plusieurs reprise sur l'ordinateur identifier au reseau :"+s.NameComputer();
                                s.envoyerEmail(Mes, expediteur,sujet);
                                
                                  JOptionPane.showMessageDialog(this,"En essayant de penetrer plusieurs  fois le systeme Vous avez ete Bloque \n veuillez contacter un administrateur");
                                  mato.SupprimerTentative(nomUsers);
                                break;
                            default:
                                JOptionPane.showMessageDialog(this,"mot de passe incorrecte \n" + "Tenatative restant: " + restant,"Erreur",JOptionPane.ERROR_MESSAGE);
                                break;
                        }
                       
                        txtMotPasse.setText("");
                        txtMotPasse.setText("");
                    }

                }
              
          
           
           // si itilizate a inactif
              else if("0".equals(etat)){
                   JOptionPane.showMessageDialog(null,"Vous  avez ete bloquer veuillez Contacter un administrateur","Erreur",JOptionPane.ERROR_MESSAGE);
              }
              
              // si nom itilizate a bon , mot pas la bon , li actif
              else{
                    // JOptionPane.showMessageDialog(FenConnexion.this,"li bon");
                 //    System.out.println(FicheLogin.get(1));
                
                  
                   int nombreconnex=mato.CompterConnexion(code);
                   
                    
             InterfaceEmployer mati=(InterfaceEmployer) cont.lookup(ser.getEmploye());
             ArrayList<String> FicheEmployer;
             FicheEmployer=mati.FicheEmployer(code);
             FenMenuUniv fen=new FenMenuUniv(); 
             
                  //System.out.println(FicheEmployer.get(1));
               
             fen.lblnom.setText(FicheEmployer.get(1));
             fen.lblprenom.setText(FicheEmployer.get(2));
             fen.lblfonction.setText(FicheEmployer.get(10));
           //  fen.lblimage.setText(FicheEmployer.get(12));
            
                            
             
             // si se premye fwa moun nan ap konekte
             if(nombreconnex==0){
             
             
           
  
            
                  int i = 0;
                  String nom1=null;
                   String pass=null;
                   
                   // yn boucle ki pemet moun nan chanje nonl  oubyen li toujou kenbe mem non itilisate a 
        
        do {
 
          
                 int nom2;
    try{
                nom1=JOptionPane.showInputDialog(this,"Entrez Un Nouveau Nom D'utilisateur").trim();
                nom2=nom1.length();
               
             }
             catch(Exception dd){
             nom2=0;
             }
    
    // si moun nan antre yn nouvo non
    if(nom2>0){
                i++;
                mato.ModifierNomUtilisateur(nom1, code);
               }
    
    // si li pa antre non 
               else{
        // pozel yn kesyon 
               int answer = JOptionPane.showConfirmDialog(this, 
		" Vous Avez Rien Entrez \n Voulez Vous Gardez Votre  Nom D'utilisateur", "Message", 
        JOptionPane.YES_NO_OPTION);
               
 
if (answer == JOptionPane.NO_OPTION) {
	nom2=0;
}
// si moun nan dako poul kenbe menm non an bal pase
else if(answer == JOptionPane.YES_OPTION) {
  	
        i++;
}
               }
           
           
        }

        // tout tan moun pa swa chanje non an oubyen dako lp kenbe menm non an repte aksyon an
        while (i < 1);
        
        // deuxiemen test
        i=0;
           // yn boucle ki pemet moun nan chanje mot de passe la   oubyen li toujou kenbe mem non itilisate a        
        do {
 
          
                 int nom2=0;
    try{
                pass=JOptionPane.showInputDialog(this,"Entrez Un Nouveau Mot de Passe").trim();
                nom2=pass.length();
               
             }
             catch(Exception dd){
             nom2=0;
             }
     // si moun nan antre yn nouvo pass
    if(nom2>0){
                i++;
                mato.ModifierPassUtilisateur(pass, code);
               }
        // si li pa antre non 
               else{
         // pozel yn kesyon 
               int answer = JOptionPane.showConfirmDialog(this, 
		" Vous Avez Rien Entrez \n Voulez Vous Gardez Votre ancien Mot de Passe", "Message", 
        JOptionPane.YES_NO_OPTION);

if (answer == JOptionPane.NO_OPTION) {
	nom2=0;
}
// si moun nan dako poul kenbe menm pass lan bal pase
else if(answer == JOptionPane.YES_OPTION) {
  	
        i++;
}
               }
           
           
        }
 
        // Test expression
         // tout tan moun pa swa chanje pass an oubyen dako lp kenbe menm pass lan repete aksyon an
        while (i < 1);
             }
             // finissement
             
           
                  invisible(fen);// mete tout sous menu no cliquable
                  // si li jwenn moun nan sa se yn employer
             if( null != FicheEmployer.get(10))
                 // repartition tache
                 switch (FicheEmployer.get(10)) {
                 
                     case "Secretaire":
      fen.smnInsEtudiant.setEnabled(true);
      fen.smnrecheretudiant.setEnabled(true);
      fen.smnlisteretudiant.setEnabled(true);
      fen.smndepot.setEnabled(true);
                         break;
                     case "Administrateur":
      fen.smnprofesseur.setEnabled(true);
      fen.smnevaluation.setEnabled(true);
      fen.smnInsEtudiant.setEnabled(true);
      fen.smnrecheretudiant.setEnabled(true);
      fen.smnlisteretudiant.setEnabled(true);
      fen.smnoptionscours.setEnabled(true);
      fen.smnbulletin.setEnabled(true);
      fen.smnmodalitepaiement.setEnabled(true);
      fen.smndepot.setEnabled(true);
      fen.smnlistemodpaie.setEnabled(true);
      fen.smnlisteancpaie.setEnabled(true);
      fen.smnlistetransactions.setEnabled(true);
      fen.smngestemployer.setEnabled(true);
      fen.smnlisteemploye.setEnabled(true);
      fen.smncreerutlisateur.setEnabled(true);
      fen.smnrechutilisasteur.setEnabled(true);
                         break;
                     case "Coordonnateur":
      fen.smnprofesseur.setEnabled(true);
      fen.smnevaluation.setEnabled(true);
      fen.smnoptionscours.setEnabled(true);
      fen.smnbulletin.setEnabled(true);
                         break;
                     case "Comptable":
                     
 
      fen.smnmodalitepaiement.setEnabled(true);
      fen.smndepot.setEnabled(true);
      fen.smnlistemodpaie.setEnabled(true);
      fen.smnlisteancpaie.setEnabled(true);
      fen.smnlistetransactions.setEnabled(true);
    
                         break;
                         
                         case "Gestionnaire RH":
      fen.smngestemployer.setEnabled(true);
      fen.smnlisteemploye.setEnabled(true);
      fen.smncreerutlisateur.setEnabled(true);
      fen.smnrechutilisasteur.setEnabled(true);
                         break;
                     default:
                         JOptionPane.showMessageDialog(null,"Cet Fonction est incorecte","Erreur",JOptionPane.ERROR_MESSAGE);
                         break;
                 }
          
             // tout enregistrer le moun nan konekte sou systeme lan 
              mato.EnregistrerConnexion(code,  s.NameComputer());
              // ouve menu an 
              if(FicheEmployer.get(12)!=null){
                  TransfererFichier img=new TransfererFichier();
                  img.recevoirFichier(FicheEmployer.get(12));
                  
                  
                }
                else{
                
                }
              ImageIcon  icon=new ImageIcon(FicheEmployer.get(12));
      Image image=icon.getImage().getScaledInstance(32, 32, Image.SCALE_SMOOTH);
      icon = new ImageIcon(image);
       fen.lblimage.setIcon(icon);
             fen.show();
             this.dispose();
              }
                }
             // finissement else verification info vide
             
              
         } catch (NamingException | RemoteException ex) {
          JOptionPane.showMessageDialog(null,"le serveur n'est pas connecte veuillez reesayer plus tard ","Erreur",JOptionPane.ERROR_MESSAGE);
         }
        
     
    }//GEN-LAST:event_btnloginActionPerformed

    private void jPanel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel4PropertyChange

//        java.util.Timer timer = new java.util.Timer();
//
//        counter = FenConnexion.tim ;
//
//        TimerTask task = new TimerTask(){
//            public void run(){
//                tm.setText(Integer.toString(counter));
//                sec.setText("Secondes");
//                counter --;
//                if(counter == 0){
//                    sec.setText("Seconde");
//                }else if(counter == -1){
//                    timer.cancel();
//                    sec.setText("Seconde");
//                }else if(isIt){
//                    timer.cancel();
//                    isIt = false;
//                }
//            }
//        };
//        timer.scheduleAtFixedRate(task, 1000, 1000);
    }//GEN-LAST:event_jPanel4PropertyChange
void invisible(FenMenuUniv fen){
      fen.smnprofesseur.setEnabled(false);
      fen.smnevaluation.setEnabled(false);
      fen.smnInsEtudiant.setEnabled(false);
      fen.smnrecheretudiant.setEnabled(false);
      fen.smnlisteretudiant.setEnabled(false);
      fen.smnoptionscours.setEnabled(false);
      fen.smnbulletin.setEnabled(false);
      fen.smnmodalitepaiement.setEnabled(false);
      fen.smndepot.setEnabled(false);
      fen.smnlistemodpaie.setEnabled(false);
      fen.smnlisteancpaie.setEnabled(false);
      fen.smnlistetransactions.setEnabled(false);
      fen.smngestemployer.setEnabled(false);
      fen.smnlisteemploye.setEnabled(false);
      fen.smncreerutlisateur.setEnabled(false);
      fen.smnrechutilisasteur.setEnabled(false);
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblforgot;
    private javax.swing.JLabel lblhello;
    private javax.swing.JLabel lblmot;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblpseudo;
    private javax.swing.JLabel lbltxtuser;
    private javax.swing.JLabel sec;
    private javax.swing.JLabel show;
    private javax.swing.JLabel tm;
    private javax.swing.JPasswordField txtMotPasse;
    private javax.swing.JTextField txtNomUser;
    // End of variables declaration//GEN-END:variables
}
