/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.intense.vue;


import com.uni.intense.presentation.InterfaceProfesseur;
import com.uni.intense.presentation.InterfaceService;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ServiceReseau;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
/**
 *
 * @author kelly
 */
public class PanAttributionCours extends javax.swing.JPanel {
ServiceReseau ser=new ServiceReseau();

    /**
     * Creates new form PanCours
     */
    public PanAttributionCours() {
        initComponents();
         pancomposant.setVisible(false);
            try {
                    
                
                    ArrayList<String> Al;
                    Context cont=new InitialContext();
                  InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
                    Al=  mato.remplirComboOptions();
                     int i=0;
        for(String dep:Al)
        {
            cbxoptioncours.addItem(dep);
            i++;
        }
                } catch (NamingException ex) {
                    Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcodeprof1 = new javax.swing.JLabel();
        txtcodeprofcours = new javax.swing.JTextField();
        btnrecherprofcours = new javax.swing.JButton();
        pancomposant = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbxoptioncours = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbxcours = new javax.swing.JComboBox<>();
        lblcour = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listcours = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btndissicier = new javax.swing.JButton();
        btnassocier = new javax.swing.JButton();
        btnnewseach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxniveau = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxsession = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxvacation = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtinfo = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcodeprof1.setText("Code du professeur :");
        add(lblcodeprof1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        txtcodeprofcours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodeprofcoursKeyTyped(evt);
            }
        });
        add(txtcodeprofcours, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 165, -1));

        btnrecherprofcours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnrecherprofcours.setText("Rechercher");
        btnrecherprofcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecherprofcoursActionPerformed(evt);
            }
        });
        add(btnrecherprofcours, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        pancomposant.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Option");

        cbxoptioncours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxoptioncoursActionPerformed(evt);
            }
        });

        jLabel19.setText("Cours");

        cbxcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcoursActionPerformed(evt);
            }
        });

        lblcour.setText("Informations :");

        listcours.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listcoursValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listcours);

        jLabel21.setText("Attribuer Un Cours");

        jLabel22.setText("Cours Deja Attribuer");

        btndissicier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apprentissage-en-ligne.png"))); // NOI18N
        btndissicier.setText("Desattribuer ce Cours a cet professeur");
        btndissicier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndissicierActionPerformed(evt);
            }
        });

        btnassocier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apprentissage-en-ligne.png"))); // NOI18N
        btnassocier.setText("Attribuer ce Cours a cet professeur");
        btnassocier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassocierActionPerformed(evt);
            }
        });

        btnnewseach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnnewseach.setText("Rechercher Un Nouveau Professeur");
        btnnewseach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewseachActionPerformed(evt);
            }
        });

        jLabel1.setText("Niveau: ");

        cbxniveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbxniveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxniveauActionPerformed(evt);
            }
        });

        jLabel2.setText("Session :");

        cbxsession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cbxsession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsessionActionPerformed(evt);
            }
        });

        jLabel3.setText("Vacation :");

        cbxvacation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Median", "Matin", "Soir", "Week-End" }));
        cbxvacation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxvacationActionPerformed(evt);
            }
        });

        txtinfo.setColumns(20);
        txtinfo.setRows(5);
        jScrollPane1.setViewportView(txtinfo);

        javax.swing.GroupLayout pancomposantLayout = new javax.swing.GroupLayout(pancomposant);
        pancomposant.setLayout(pancomposantLayout);
        pancomposantLayout.setHorizontalGroup(
            pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pancomposantLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnassocier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndissicier)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pancomposantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pancomposantLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnnewseach)
                        .addGap(37, 37, 37))
                    .addGroup(pancomposantLayout.createSequentialGroup()
                        .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pancomposantLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pancomposantLayout.createSequentialGroup()
                                .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pancomposantLayout.createSequentialGroup()
                                        .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel19))
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxcours, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbxsession, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pancomposantLayout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(29, 29, 29)
                                            .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cbxniveau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxoptioncours, 0, 179, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pancomposantLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblcour))
                            .addGroup(pancomposantLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbxvacation, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(329, 329, 329)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        pancomposantLayout.setVerticalGroup(
            pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pancomposantLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnnewseach)
                .addGap(38, 38, 38)
                .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pancomposantLayout.createSequentialGroup()
                        .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(pancomposantLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel17)
                                    .addComponent(cbxoptioncours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxniveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pancomposantLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcour)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pancomposantLayout.createSequentialGroup()
                        .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pancomposantLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cbxsession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(cbxcours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbxvacation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(pancomposantLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pancomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnassocier)
                            .addComponent(btndissicier))
                        .addGap(58, 58, 58))))
        );

        add(pancomposant, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 139, -1, -1));

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestion Attribution Cours");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(370, 370, 370))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 70));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 970, 60));
    }// </editor-fold>//GEN-END:initComponents
void lister() throws NamingException, RemoteException{
        String idprof=txtcodeprofcours.getText().trim();
               

                Context cont=new InitialContext();
                InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());

                String [] bd=mato.remplirlisetecours(idprof);

                listcours.setModel(new javax.swing.AbstractListModel() {
                    String[] strings =bd;
                    @Override
                    public int getSize() { return strings.length; }
                    @Override
                    public Object getElementAt(int i) { return strings[i]; }
                });
}
    private void btnrecherprofcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecherprofcoursActionPerformed
        try {
           
            String id_prof=txtcodeprofcours.getText().trim();
            ArrayList<String> fiche;
            Context cont1=new InitialContext();
            InterfaceProfesseur mato1=(InterfaceProfesseur) cont1.lookup(ser.getProfesseur());
            fiche= mato1.FicheProfesseur(id_prof);
            String id_prof2=fiche.get(0);
            if(id_prof.equals(id_prof2)){
            
                lister();
                pancomposant.setVisible(true);
                lblcodeprof1.setVisible(false);
                txtcodeprofcours.setVisible(false);
                btnrecherprofcours.setVisible(false);

            }
            else{
                pancomposant.setVisible(false);
                JOptionPane.showMessageDialog(PanAttributionCours.this,"Le code du professeur est incorect");

            }
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnrecherprofcoursActionPerformed

    private void cbxoptioncoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxoptioncoursActionPerformed
        // TODO add your handling code here:
        cbxcours.removeAllItems();
        String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
             String Niveau=cbxniveau.getSelectedItem().toString();
             
        String Session=cbxsession.getSelectedItem().toString();
        try {

          
            ArrayList<String> Al=new ArrayList<>();
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            Al=  mato.remplirComboCours(Nom_Opt, Niveau, Session);
            int i=0;

            for(String dep:Al)
            {
                cbxcours.addItem(dep);

                i++;
            }
        } catch (NamingException ex) {
            Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxoptioncoursActionPerformed

    private void cbxcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcoursActionPerformed
        // TODO add your handling code here:
        //                try{
            //                String Cours=cbxcours.getSelectedItem().toString();
            //                lblcour1.setText(Cours);
            //                }
        //                catch(Exception e){}
    }//GEN-LAST:event_cbxcoursActionPerformed

    private void listcoursValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listcoursValueChanged
    try {
        // TODO add your handling code here:
        String courscs=listcours.getSelectedValue();
       
        
        Context cont=new InitialContext();
        InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
        String info=mato.InformationCoursSelect(courscs);
        txtinfo.setText(info);
    } catch (NamingException ex) {
        Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
    } catch (RemoteException ex) {
        Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }//GEN-LAST:event_listcoursValueChanged

    private void btndissicierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndissicierActionPerformed
    try {
        // TODO add your handling code here:
        String courscs=listcours.getSelectedValue();
        if(courscs==null){
          JOptionPane.showMessageDialog(null,"Veuillez Selectionnez un Cours","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        else{
       
        Context cont=new InitialContext();
        InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
        String mes=mato.SuprimmerAttributionCours(courscs);
        JOptionPane.showMessageDialog(PanAttributionCours.this,mes);
        lister();
        }
    } catch (NamingException | RemoteException ex) {
        Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btndissicierActionPerformed

    private void btnassocierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassocierActionPerformed
        try {
            // TODO add your handling code here:
         
            String Idprof=txtcodeprofcours.getText().trim();
            String Nom_Cours=cbxcours.getSelectedItem().toString();
             String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
           String Vacation=cbxvacation.getSelectedItem().toString();
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            String mes=mato.EnregistrerCoursSelectionner(Idprof, Nom_Opt, Nom_Cours,Vacation);
            JOptionPane.showMessageDialog(PanAttributionCours.this,mes);
            lister();
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnassocierActionPerformed

    private void btnnewseachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewseachActionPerformed
        // TODO add your handling code here:
        pancomposant.setVisible(false);
        lblcodeprof1.setVisible(true);
        txtcodeprofcours.setVisible(true);
        btnrecherprofcours.setVisible(true);

    }//GEN-LAST:event_btnnewseachActionPerformed

    private void cbxniveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxniveauActionPerformed
        // TODO add your handling code here:
          cbxcours.removeAllItems();
        String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
             String Niveau=cbxniveau.getSelectedItem().toString();
             
        String Session=cbxsession.getSelectedItem().toString();
        try {

     
            ArrayList<String> Al=new ArrayList<>();
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            Al=  mato.remplirComboCours(Nom_Opt, Niveau, Session);
            int i=0;

            for(String dep:Al)
            {
                cbxcours.addItem(dep);

                i++;
            }
        } catch (NamingException ex) {
            Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_cbxniveauActionPerformed

    private void cbxsessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsessionActionPerformed
        // TODO add your handling code here:
         cbxcours.removeAllItems();
        String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
             String Niveau=cbxniveau.getSelectedItem().toString();
             
        String Session=cbxsession.getSelectedItem().toString();
        try {

         
            ArrayList<String> Al=new ArrayList<>();
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            Al=  mato.remplirComboCours(Nom_Opt, Niveau, Session);
            int i=0;

            for(String dep:Al)
            {
                cbxcours.addItem(dep);

                i++;
            }
        } catch (NamingException ex) {
            Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxsessionActionPerformed

    private void cbxvacationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxvacationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxvacationActionPerformed

    private void txtcodeprofcoursKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodeprofcoursKeyTyped
        // TODO add your handling code here:
        Contrainte co=new Contrainte();
        co.isletterdigit(evt);
    }//GEN-LAST:event_txtcodeprofcoursKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnassocier;
    private javax.swing.JButton btndissicier;
    private javax.swing.JButton btnnewseach;
    private javax.swing.JButton btnrecherprofcours;
    private javax.swing.JComboBox<String> cbxcours;
    private javax.swing.JComboBox<String> cbxniveau;
    private javax.swing.JComboBox<String> cbxoptioncours;
    private javax.swing.JComboBox<String> cbxsession;
    private javax.swing.JComboBox<String> cbxvacation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcodeprof1;
    private javax.swing.JLabel lblcour;
    private javax.swing.JList<String> listcours;
    private javax.swing.JPanel pancomposant;
    private javax.swing.JTextField txtcodeprofcours;
    private javax.swing.JTextArea txtinfo;
    // End of variables declaration//GEN-END:variables
}
