 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.intense.vue;


import com.uni.intense.presentation.InterfaceEvaluationsNormal;
import com.uni.intense.presentation.InterfaceService;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ServiceReseau;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level; 
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kelly
 */
public class PanEvaluation extends javax.swing.JPanel {
ServiceReseau ser=new ServiceReseau();

 public TableRowSorter<TableModel> sorter;
    /**
     * Creates new form FenEvaluation
     */
    public PanEvaluation() {
        initComponents();
       
        SpinnerNumberModel model = new SpinnerNumberModel(30, 5, 100, 5);
        spincoef.setModel(model);
    try {
        lister();
     
    } catch (NamingException | RemoteException ex) {
        Logger.getLogger(PanEvaluation.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbxtype = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxdescrip = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        spincoef = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        txtcodepalmares = new javax.swing.JTextField();
        btnenregistrer = new javax.swing.JButton();
        btnrecher = new javax.swing.JButton();
        txtcodeeval = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Type d'evaluation");

        cbxtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intra", "Final", "Reprise" }));

        jLabel7.setText("Description du Type Choisi :");

        cbxdescrip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Examen", "Devoir" }));

        jLabel6.setText("Coefficient");

        jLabel1.setText("Code du Palmares :");

        txtcodepalmares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodepalmaresActionPerformed(evt);
            }
        });
        txtcodepalmares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodepalmaresKeyTyped(evt);
            }
        });

        btnenregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ajouter.png"))); // NOI18N
        btnenregistrer.setText("Enregistrer");
        btnenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenregistrerActionPerformed(evt);
            }
        });

        btnrecher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnrecher.setText("Trouver le code de cet Evaluation");
        btnrecher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecherActionPerformed(evt);
            }
        });

        txtcodeeval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodeevalKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnenregistrer)
                .addGap(114, 114, 114)
                .addComponent(btnrecher)
                .addGap(16, 16, 16)
                .addComponent(txtcodeeval, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(txtcodepalmares, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(cbxdescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)
                        .addComponent(cbxtype, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(spincoef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtcodepalmares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxdescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbxtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(spincoef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnenregistrer)
                    .addComponent(btnrecher)
                    .addComponent(txtcodeeval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 140));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 223, 1190, 320));

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion Evaluation");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(jLabel3)
                .addContainerGap(608, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodepalmaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodepalmaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodepalmaresActionPerformed

    private void btnenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenregistrerActionPerformed
        try {
            // TODO add your handling code here:
            String Codepalmares=txtcodepalmares.getText().trim();
            String TypesNormal =cbxtype.getSelectedItem().toString();
            String DescriptionsNormal=cbxdescrip.getSelectedItem().toString();
            String coe= spincoef.getValue().toString();
            int CoeficientNormal=Integer.parseInt(coe);
            
            if(Codepalmares.isEmpty()){
              JOptionPane.showMessageDialog(null,"Tous les champs doivent etres remplis","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else if(CoeficientNormal<=10){
              JOptionPane.showMessageDialog(null,"Le coefficient doit etre Superieur a 10","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else{
                 
            Context cont=new InitialContext();
            InterfaceEvaluationsNormal mato=(InterfaceEvaluationsNormal) cont.lookup(ser.getEvaluation());
            String message=mato.EnregistrerEvaluation(Codepalmares, TypesNormal, DescriptionsNormal, CoeficientNormal);
                JOptionPane.showMessageDialog(PanEvaluation.this,message);
                lister();
            }
      
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanEvaluation.class.getName()).log(Level.SEVERE, null, ex);
        }
                             
        
    }//GEN-LAST:event_btnenregistrerActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnrecherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecherActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            String Codepalmares=txtcodepalmares.getText().trim();
            String TypesNormal =cbxtype.getSelectedItem().toString();
            String DescriptionsNormal=cbxdescrip.getSelectedItem().toString();
          
            
            if(Codepalmares.isEmpty()){
              JOptionPane.showMessageDialog(null,"Entrer le code du palmares","Erreur",JOptionPane.ERROR_MESSAGE);
            }
           
            else{
                 
            Context cont=new InitialContext();
            InterfaceEvaluationsNormal mato=(InterfaceEvaluationsNormal) cont.lookup(ser.getEvaluation());
            String message=mato.RechercherCodeEvaluation(Codepalmares, TypesNormal, DescriptionsNormal);
                
            txtcodeeval.setText(message);
            
             if(message==null){
                    JOptionPane.showMessageDialog(null,"Cet Evaluation  n'est pas encore creer","Erreur",JOptionPane.ERROR_MESSAGE);
            }
               
            }
      
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanEvaluation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnrecherActionPerformed

    private void txtcodepalmaresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodepalmaresKeyTyped
        // TODO add your handling code here:
        Contrainte co=new Contrainte();
        co.isletterdigit(evt);
    }//GEN-LAST:event_txtcodepalmaresKeyTyped

    private void txtcodeevalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodeevalKeyTyped
        // TODO add your handling code here:
        Contrainte co=new Contrainte();
        co.isletterdigit(evt);
    }//GEN-LAST:event_txtcodeevalKeyTyped

 void lister() throws NamingException, RemoteException{
                 
                   Context cont=new InitialContext();
             InterfaceEvaluationsNormal mato=(InterfaceEvaluationsNormal) cont.lookup(ser.getEvaluation());
            String [][] maliste=mato.ListerEvaluation();
            
            
      
String[] titre= {"code","Options", "Cours", "Session","Niveau","Promotion","Vacation", "Palmares", "TypesEvaluation","Description","Coefficient"};

 DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
 sorter = new TableRowSorter<>(model);
      jTable1.setRowSorter(sorter);

 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenregistrer;
    private javax.swing.JButton btnrecher;
    private javax.swing.JComboBox<String> cbxdescrip;
    private javax.swing.JComboBox<String> cbxtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spincoef;
    private javax.swing.JTextField txtcodeeval;
    private javax.swing.JTextField txtcodepalmares;
    // End of variables declaration//GEN-END:variables
}
