/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.intense.vue;



import com.uni.intense.presentation.InterfaceProfesseur;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.DocFilterJava;
import com.uni.intense.service.ImageFilterJava;
import com.uni.intense.service.ServiceInterNet;
import com.uni.intense.service.ServiceReseau;
import com.uni.intense.service.TransfererFichier;
import java.awt.Image;
import java.io.File;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat; 
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author kelly
 */
public class PanGestionProfesseur extends javax.swing.JPanel {
  private String Id_prof;
    private String Matricule_prof;
    private String Nom_prof;
    private String Prenom_prof;
    private String Sexe_prof;
    private String Tel_prof;
    private String Email_prof;
    private String Adresse_prof;
    private String NumrefProf;
    private String DateNaissance_prof;
    private String professionprof;
    private String Etat_prof;
      private String FilenameImg;
      private String NameImg;
      private String urlphoto;
      private String urldoc;
       private String filenamedoc;
      private String namedoc;
      String Images="src//Image//personne2.png";
ServiceInterNet s=new ServiceInterNet();
   ServiceReseau ser=new ServiceReseau();
    Contrainte co=new Contrainte();

    /**
     * Creates new form PanProfesseur
     */
    public PanGestionProfesseur() {
        initComponents();
    rdbseach.setSelected(false);
        lblcodeprof.setVisible(false);
        txtcodeprof.setVisible(false);
        btnrechercherprof.setVisible(false);
        btnmodifprof.setVisible(false);
        btnmodifcv.setVisible(false);
        btnmodifimg.setVisible(false);
        btnenregprof.setVisible(true);
        btnopendoc.setVisible(false);
        dada();
    afficherImage(Images);
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbEnreg = new javax.swing.JRadioButton();
        rdbseach = new javax.swing.JRadioButton();
        lblcodeprof = new javax.swing.JLabel();
        txtcodeprof = new javax.swing.JTextField();
        btnrechercherprof = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtnomprof = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprenomprof = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxsexeprof = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbxEtat = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtemailprof = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadresseprof = new javax.swing.JTextPane();
        btnenregprof = new javax.swing.JButton();
        btnmodifprof = new javax.swing.JButton();
        txtnumref = new javax.swing.JFormattedTextField();
        txttelprof = new javax.swing.JFormattedTextField();
        txtmatriculeprof = new javax.swing.JFormattedTextField();
        lblimage = new javax.swing.JLabel();
        btnuploadimage = new javax.swing.JButton();
        btnmodifimg = new javax.swing.JButton();
        btnuploadDoc = new javax.swing.JButton();
        btnmodifcv = new javax.swing.JButton();
        btnopendoc = new javax.swing.JButton();
        jDtnaissance = new com.toedter.calendar.JDateChooser();
        cmbprofession = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 608));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdbEnreg.setSelected(true);
        rdbEnreg.setText("Embaucher");
        rdbEnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEnregActionPerformed(evt);
            }
        });
        add(rdbEnreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 53, -1, -1));

        rdbseach.setText("Rechercher");
        rdbseach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbseachActionPerformed(evt);
            }
        });
        add(rdbseach, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 53, -1, -1));

        lblcodeprof.setText("Code :");
        add(lblcodeprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 141, -1, -1));

        txtcodeprof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodeprofKeyTyped(evt);
            }
        });
        add(txtcodeprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 138, 139, -1));

        btnrechercherprof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnrechercherprof.setText("Rechercher");
        btnrechercherprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherprofActionPerformed(evt);
            }
        });
        add(btnrechercherprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 138, -1, -1));

        jLabel12.setText("Nom :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 222, -1, 20));

        txtnomprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomprofActionPerformed(evt);
            }
        });
        txtnomprof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomprofKeyTyped(evt);
            }
        });
        add(txtnomprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 220, 146, -1));

        jLabel11.setText("Prenom :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 223, 51, -1));

        txtprenomprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomprofActionPerformed(evt);
            }
        });
        txtprenomprof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprenomprofKeyTyped(evt);
            }
        });
        add(txtprenomprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 220, 146, -1));

        jLabel23.setText("Date de naissance");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 215, -1, -1));

        jLabel13.setText("Sexe :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 306, -1, -1));

        cbxsexeprof.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculin", "Feminin" }));
        add(cbxsexeprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 303, 146, -1));

        jLabel20.setText("Cin :");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 304, -1, 20));

        jLabel24.setText("Numero de Reference");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 302, -1, 20));

        jLabel14.setText("Telephone:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 424, -1, -1));

        jLabel25.setText("Profession :");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 408, -1, 20));

        jLabel26.setText("Etat :");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 410, -1, -1));

        cbxEtat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actif", "Passif" }));
        add(cbxEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 407, 146, -1));

        jLabel16.setText("Email:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 535, -1, -1));

        txtemailprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailprofActionPerformed(evt);
            }
        });
        add(txtemailprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 532, 146, -1));

        jLabel15.setText("Adresse");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 527, -1, -1));

        jScrollPane1.setViewportView(txtadresseprof);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 492, 325, 82));

        btnenregprof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add-User-icon.png"))); // NOI18N
        btnenregprof.setText("Enregistrer");
        btnenregprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenregprofActionPerformed(evt);
            }
        });
        add(btnenregprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 492, -1, -1));

        btnmodifprof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit-icon.png"))); // NOI18N
        btnmodifprof.setText("Modifier");
        btnmodifprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifprofActionPerformed(evt);
            }
        });
        add(btnmodifprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 110, -1));

        try {
            txtnumref.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+509)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(txtnumref, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 292, 155, 31));

        try {
            txttelprof.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+509)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(txttelprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 418, 148, 28));

        try {
            txtmatriculeprof.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(txtmatriculeprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 303, 146, -1));
        add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 209, 259, 259));

        btnuploadimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_24px.png"))); // NOI18N
        btnuploadimage.setText("Choisir Image");
        btnuploadimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadimageActionPerformed(evt);
            }
        });
        add(btnuploadimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 492, -1, -1));

        btnmodifimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Camera-icon.png"))); // NOI18N
        btnmodifimg.setText("modifier image");
        btnmodifimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifimgActionPerformed(evt);
            }
        });
        add(btnmodifimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 492, -1, -1));

        btnuploadDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file_doc.png"))); // NOI18N
        btnuploadDoc.setText("Choisir Cv");
        btnuploadDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadDocActionPerformed(evt);
            }
        });
        add(btnuploadDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 552, -1, -1));

        btnmodifcv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update_file_24px.png"))); // NOI18N
        btnmodifcv.setText("modifier CV");
        btnmodifcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifcvActionPerformed(evt);
            }
        });
        add(btnmodifcv, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 552, -1, -1));

        btnopendoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/file-person-icon.png"))); // NOI18N
        btnopendoc.setText("Ouvrir le document");
        btnopendoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopendocActionPerformed(evt);
            }
        });
        add(btnopendoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 67, -1, -1));
        add(jDtnaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 215, 155, -1));

        cmbprofession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Docteur", "Gestionnaire", "Informaticien", "Agronome", "Avocat", "Mathematicien", "Ingenieur Civil", "Infirmier", "Mecanicien" }));
        add(cmbprofession, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 140, -1));

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion Professeur");
        jPanel1.add(jLabel1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));
    }// </editor-fold>//GEN-END:initComponents
final void afficherImage(String urlphoto){
ImageIcon  icon=new ImageIcon(urlphoto);
      Image image=icon.getImage().getScaledInstance(259, 259, Image.SCALE_SMOOTH);
      icon = new ImageIcon(image);
       lblimage.setIcon(icon);
}
    private void rdbEnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEnregActionPerformed
        // TODO add your handling code here:
           if(!rdbEnreg.isSelected()){
            System.out.println("li  selectionnr");
 rdbseach.setSelected(true);
            rdbEnreg.setSelected(false);
            lblcodeprof.setVisible(true);
            txtcodeprof.setVisible(true);
            btnrechercherprof.setVisible(true);
            btnmodifprof.setVisible(false);
            btnenregprof.setVisible(false);
             btnmodifcv.setVisible(false);
        btnmodifimg.setVisible(false);
         btnuploadimage.setVisible(false);
        btnuploadDoc.setVisible(false);
        btnopendoc.setVisible(false);
            renitialiserPanProfesseur();
        }
        else{
            rdbEnreg.setSelected(true);
            rdbseach.setSelected(false);
            lblcodeprof.setVisible(false);
            txtcodeprof.setVisible(false);
            btnrechercherprof.setVisible(false);
            btnmodifprof.setVisible(false);
            btnenregprof.setVisible(true);
             btnmodifcv.setVisible(false);
        btnmodifimg.setVisible(false);
             btnopendoc.setVisible(false);
         btnuploadimage.setVisible(true);
        btnuploadDoc.setVisible(true);
        
            renitialiserPanProfesseur();
        }
    }//GEN-LAST:event_rdbEnregActionPerformed

    private void rdbseachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbseachActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
           if(!rdbseach.isSelected()){
            System.out.println("li  selectionnr");
            rdbEnreg.setSelected(true);
                 btnopendoc.setVisible(false);
            rdbseach.setSelected(false);
            lblcodeprof.setVisible(false);
            txtcodeprof.setVisible(false);
            btnrechercherprof.setVisible(false);
            btnmodifprof.setVisible(false);
            btnenregprof.setVisible(true);
             btnmodifcv.setVisible(false);
        btnmodifimg.setVisible(false);
         btnuploadimage.setVisible(true);
        btnuploadDoc.setVisible(true);
            renitialiserPanProfesseur();
        }
        else{
            rdbseach.setSelected(true);
            rdbEnreg.setSelected(false);
            lblcodeprof.setVisible(true);
            txtcodeprof.setVisible(true);
            btnrechercherprof.setVisible(true);
            btnmodifprof.setVisible(false);
            btnenregprof.setVisible(false);
             btnmodifcv.setVisible(false);
        btnmodifimg.setVisible(false);
         btnuploadimage.setVisible(false);
        btnuploadDoc.setVisible(false);
             btnopendoc.setVisible(false);
            renitialiserPanProfesseur();
        }
    }//GEN-LAST:event_rdbseachActionPerformed

    void rechercher(String id_prof){
try{
      
           
            if(id_prof == null){
                    JOptionPane.showMessageDialog(null,"entrer un code","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else{
            ArrayList<String> fiche;
            Context cont=new InitialContext();
            InterfaceProfesseur mato=(InterfaceProfesseur) cont.lookup(ser.getProfesseur());
            fiche= mato.FicheProfesseur(id_prof);
            String id_prof2=fiche.get(0);
            if(id_prof.equals(id_prof2)){
                Id_prof=fiche.get(0);
                txtmatriculeprof.setText(fiche.get(1));
                txtnomprof.setText(fiche.get(2));
                txtprenomprof.setText(fiche.get(3));
                cbxsexeprof.setSelectedItem(fiche.get(4));
                txttelprof.setText(fiche.get(5));
                txtemailprof.setText(fiche.get(6));
                txtadresseprof.setText(fiche.get(7));
                txtnumref.setText(fiche.get(8));
                String datee=fiche.get(9);
		Date date = new SimpleDateFormat("yyyy/MM/dd").parse(datee);
                jDtnaissance.setDate(date);
                cmbprofession.setSelectedItem(fiche.get(10));
                     //txtprofession.setText(datee);
                cbxEtat.setSelectedItem(fiche.get(11));
                 urlphoto=fiche.get(12);
                  urldoc=fiche.get(13);
               
                
                
                btnmodifcv.setVisible(true);
                btnmodifprof.setVisible(true);
                btnmodifimg.setVisible(true);
                     
                if(urlphoto!=null){
                  TransfererFichier img=new TransfererFichier();
                  img.recevoirFichier(urlphoto);
                  afficherImage(urlphoto);
                  img.effacerFichierClient(urlphoto); 
                }
                
                 if(urldoc!=null){
                  TransfererFichier img=new TransfererFichier();
                  img.recevoirFichier(urldoc); 
                  btnopendoc.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Le code est incorrect","Erreur",JOptionPane.ERROR_MESSAGE);
                  btnmodifcv.setVisible(false);
                btnmodifprof.setVisible(false);
                btnmodifimg.setVisible(false);
                     btnopendoc.setVisible(false);
                urlphoto=null;
                urldoc=null;
                renitialiserPanProfesseur();
                
            }
            }
            //   JOptionPane.showMessageDialog(FenMenuEtudiant.this,gu);
        } catch (NamingException | RemoteException | ParseException ex) {
            Logger.getLogger(PanGestionProfesseur.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void btnrechercherprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherprofActionPerformed
        // TODO add your handling code here:
        String id=txtcodeprof.getText().trim();
        rechercher(id);
    }//GEN-LAST:event_btnrechercherprofActionPerformed

 
    private void txtnomprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomprofActionPerformed

    private void txtprenomprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomprofActionPerformed

    private void txtemailprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailprofActionPerformed

    final void dada(){
    String datenai="2000/12/31";
           String datenai2="1950/01/30";
           try {
            
            Date date=new SimpleDateFormat("yyyy/MM/dd").parse(datenai);
      jDtnaissance.setMaxSelectableDate(date);
       jDtnaissance.setDate(date);
        } catch (ParseException ex) {
            
        }
             
           try {
            
            Date date=new SimpleDateFormat("yyyy/MM/dd").parse(datenai2);
      jDtnaissance.setMinSelectableDate(date);
        } catch (ParseException ex) {
            
        }
}
    private void btnenregprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenregprofActionPerformed
        try {
            // TODO add your handling code here:
          
             Matricule_prof=txtmatriculeprof.getText().trim();
             Nom_prof=txtnomprof.getText().trim().replace("'", "''");
             Prenom_prof=txtprenomprof.getText().trim().replace("'", "''");
             Sexe_prof=cbxsexeprof.getSelectedItem().toString();
             Tel_prof=txttelprof.getText().trim();
             Email_prof=txtemailprof.getText().trim();
             Adresse_prof=txtadresseprof.getText().trim().replace("'", "''");
             int dola=0;
             try{
            Date dd = jDtnaissance.getDate();
            DateFormat format=new SimpleDateFormat("yyyy/MM/dd");
                DateNaissance_prof = format.format(dd);
                dola=1;
             }
             catch(Exception ex){
             
             dola=0;
             }

               Etat_prof=cbxEtat.getSelectedItem().toString();
               NumrefProf=txtnumref.getText().trim();
              professionprof=cmbprofession.getSelectedItem().toString();
              
           //   System.out.println(Matricule_prof.length());
                 boolean verif=s.isValid(Email_prof);
               if(Nom_prof.isEmpty()||Prenom_prof.isEmpty()||Email_prof.isEmpty()||Adresse_prof.isEmpty()||professionprof.isEmpty()){
        JOptionPane.showMessageDialog(null,"Remplissez tous les champs","Erreur",JOptionPane.ERROR_MESSAGE);
            }
        
             else if(Nom_prof.length()<=2||Prenom_prof.length()<=2){
        JOptionPane.showMessageDialog(null,"Le nom et Prenom doit avoir plus de 2 carateres","Erreur",JOptionPane.ERROR_MESSAGE);
            } 
             
                     else if(Matricule_prof.length()<12){
        JOptionPane.showMessageDialog(null,"Le Cin doit contenir 10 Chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
            } 
            else if(Tel_prof.length()<13||NumrefProf.length()<13){
        JOptionPane.showMessageDialog(null,"Les Telephones doivent avoir plus de avoir 8 chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
            }             
            
               else if(dola==0){
                JOptionPane.showMessageDialog(null,"Mettre une date de naissance","Erreur",JOptionPane.ERROR_MESSAGE);
               }
               else if(verif==false){
                JOptionPane.showMessageDialog(null,"Cet Email n'est pas valide","Erreur",JOptionPane.ERROR_MESSAGE);
            }
               else    if(FilenameImg==null||NameImg==null){
               JOptionPane.showMessageDialog(null,"Choisissez une Image","Erreur",JOptionPane.ERROR_MESSAGE);
           }
            else    if(filenamedoc==null||namedoc==null){
               JOptionPane.showMessageDialog(null,"Choisissez un document","Erreur",JOptionPane.ERROR_MESSAGE);
           }
                 
               else{
                 Context cont=new InitialContext();
            InterfaceProfesseur mato=(InterfaceProfesseur) cont.lookup(ser.getProfesseur());
            String g=  mato.EnregistrerProfesseur(Matricule_prof, Nom_prof, Prenom_prof, Sexe_prof, Tel_prof, Email_prof, Adresse_prof, NumrefProf, DateNaissance_prof, professionprof, Etat_prof);
          TransfererFichier img=new TransfererFichier();
              String fe = FilenameUtils.getExtension(FilenameImg);
                 String Code="Img"+g+"."+fe;
          String url=   img.EnvoyerFichier(FilenameImg, NameImg,Code);
          mato.ModifierUrlPhoto(g, url);
          
          TransfererFichier imgs=new TransfererFichier();
                 String fes = FilenameUtils.getExtension(filenamedoc);
                 String Codes="CV"+g+"."+fes;
          String urls=   imgs.EnvoyerFichier(filenamedoc, namedoc,Codes);
          mato.ModifierUrldoc(g, urls);
            JOptionPane.showMessageDialog(PanGestionProfesseur.this,"Proffesseur Embaucher Avec Succes","Succes",JOptionPane.INFORMATION_MESSAGE);
            renitialiserPanProfesseur();
               }
          

        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanGestionProfesseur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnenregprofActionPerformed

    private void btnmodifprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifprofActionPerformed
      try {
          // TODO add your handling code here:
       
      
       
      String    Nom_prof=txtnomprof.getText().replace("'", "''");
        String  Prenom_prof=txtprenomprof.getText().replace("'", "''");
     
        String  Tel_prof=txttelprof.getText().trim();
        String  Email_prof=txtemailprof.getText();
        String  Adresse_prof=txtadresseprof.getText().trim().replace("'", "''");
        
          
         String Etat_prof=cbxEtat.getSelectedItem().toString();
           boolean verif=s.isValid(Email_prof);
       
          if(Nom_prof.isEmpty()||Prenom_prof.isEmpty()||Email_prof.isEmpty()||Adresse_prof.isEmpty()){
        JOptionPane.showMessageDialog(null,"Remplissez tous les champs","Erreur",JOptionPane.ERROR_MESSAGE);
            }
                             if(Nom_prof.length()<=2||Prenom_prof.length()<=2){
        JOptionPane.showMessageDialog(null,"Le nom et Prenom doit avoir plus de 2 carateres","Erreur",JOptionPane.ERROR_MESSAGE);
            } 
              
               
                   else if(Tel_prof.length()!=15){
                JOptionPane.showMessageDialog(null,"Les numeros de Telephones doit contenir 8 chiffres","Erreur",JOptionPane.ERROR_MESSAGE);
               }
                    else if(verif==false){
                JOptionPane.showMessageDialog(null,"Cet Email n'est pas valide","Erreur",JOptionPane.ERROR_MESSAGE);
            }
                   else{
          Context cont=new InitialContext();
          InterfaceProfesseur mato=(InterfaceProfesseur) cont.lookup(ser.getProfesseur());
          String g=  mato.ModifierProfesseur(Nom_prof, Prenom_prof, Tel_prof, Email_prof, Adresse_prof,Etat_prof, Id_prof);
           JOptionPane.showMessageDialog(PanGestionProfesseur.this,g);
           renitialiserPanProfesseur();
                   }
      } catch (NamingException ex) {
          Logger.getLogger(PanGestionProfesseur.class.getName()).log(Level.SEVERE, null, ex);
      } catch (RemoteException ex) {
          Logger.getLogger(PanGestionProfesseur.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_btnmodifprofActionPerformed

    private void btnuploadimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadimageActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser=new JFileChooser();
         chooser.addChoosableFileFilter(new ImageFilterJava());
            chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();

             FilenameImg=f.getAbsolutePath();
              NameImg=f.getName();
           
            afficherImage(FilenameImg);
        }
        catch(Exception e){
          FilenameImg=null;
          NameImg=null;
    afficherImage(Images);
            
        }
    }//GEN-LAST:event_btnuploadimageActionPerformed

    private void btnmodifimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifimgActionPerformed
        // TODO add your handling code here:
         
        int var=0;
        JFileChooser chooser=new JFileChooser();
         chooser.addChoosableFileFilter(new ImageFilterJava());
            chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();

             FilenameImg=f.getAbsolutePath();
              NameImg=f.getName();
         
        
            afficherImage(FilenameImg);
            var=1;
        }
        catch(Exception e){
            FilenameImg=null;
            NameImg=null;
       afficherImage(Images);
            var=0;
        }
        if(var==1){
           
            TransfererFichier img=new TransfererFichier();
            if(urlphoto!=null){
                 img.effacerFichierServer(urlphoto);
            }
           

            String fe = FilenameUtils.getExtension(FilenameImg);
                 String Code="Img"+Id_prof+"."+fe;
          String url=   img.EnvoyerFichier(FilenameImg, NameImg,Code);
            try {

                Context cont=new InitialContext();
                InterfaceProfesseur mato=(InterfaceProfesseur) cont.lookup(ser.getProfesseur());
                mato.ModifierUrlPhoto(Id_prof, url);
                JOptionPane.showMessageDialog(PanGestionProfesseur.this,"Image Modifier Avec Succes"+Id_prof);
                rechercher(Id_prof);

            }

            catch (NamingException | RemoteException ex) {
                Logger.getLogger(FenEnregisterEtudiants.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnmodifimgActionPerformed

    private void btnuploadDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadDocActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.addChoosableFileFilter(new DocFilterJava());
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();

             filenamedoc=f.getAbsolutePath();
              namedoc=f.getName();
           

        }
        catch(Exception e){
           filenamedoc=null;
             namedoc=null;

        }
    }//GEN-LAST:event_btnuploadDocActionPerformed

    private void btnmodifcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifcvActionPerformed
        // TODO add your handling code here:
       
        int var=0;
        JFileChooser chooser=new JFileChooser();
        chooser.addChoosableFileFilter(new DocFilterJava());
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        try{
            File f=chooser.getSelectedFile();

             filenamedoc=f.getAbsolutePath();
              namedoc=f.getName();
           
            var=1;
        }
        catch(Exception e){
           namedoc=null;
               namedoc=null;
               
              

            var=0;
        }
        if(var==1){
            
            
            
            TransfererFichier img=new TransfererFichier();
             if(urldoc!=null){
             img.effacerFichierServer(urldoc);
             }
            
            String fe = FilenameUtils.getExtension(filenamedoc);
            String Code="Cv"+Id_prof+"."+fe;
            String url=   img.EnvoyerFichier(filenamedoc, namedoc,Code);
            try {

                Context cont=new InitialContext();
                InterfaceProfesseur mato=(InterfaceProfesseur) cont.lookup(ser.getProfesseur());
                mato.ModifierUrldoc(Id_prof, url);
                JOptionPane.showMessageDialog(PanGestionProfesseur.this,"Document Modifier Avec Succes");
                rechercher(Id_prof);

            }

            catch (NamingException | RemoteException ex) {
                Logger.getLogger(FenEnregisterEtudiants.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnmodifcvActionPerformed

    private void btnopendocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopendocActionPerformed
        // TODO add your handling code here:
        ServiceInterNet sa=new ServiceInterNet();
        sa.OpenNavigator(urldoc);
    }//GEN-LAST:event_btnopendocActionPerformed

    private void txtcodeprofKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodeprofKeyTyped
        // TODO add your handling code here:
        co.isletterdigit(evt);
    }//GEN-LAST:event_txtcodeprofKeyTyped

    private void txtprenomprofKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomprofKeyTyped
        // TODO add your handling code here:
        co.isletter(evt);
    }//GEN-LAST:event_txtprenomprofKeyTyped

    private void txtnomprofKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomprofKeyTyped
        // TODO add your handling code here:
         co.isletter(evt);
    }//GEN-LAST:event_txtnomprofKeyTyped

     void renitialiserPanProfesseur(){
         txtcodeprof.setText("");
            txtmatriculeprof.setText("");
            txtnomprof.setText("");
            txtprenomprof.setText("");
            txttelprof.setText("");
            txtemailprof.setText("");
            txtadresseprof.setText("");
            txtnumref.setText("");
            cmbprofession.setSelectedIndex(0);
            cbxsexeprof.setSelectedIndex(0);
             cbxEtat.setSelectedIndex(0);
           afficherImage(Images);
              FilenameImg=null;
        NameImg=null;
        urlphoto=null;
        urldoc=null;
         filenamedoc=null;
        namedoc=null;
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenregprof;
    private javax.swing.JButton btnmodifcv;
    private javax.swing.JButton btnmodifimg;
    private javax.swing.JButton btnmodifprof;
    private javax.swing.JButton btnopendoc;
    private javax.swing.JButton btnrechercherprof;
    private javax.swing.JButton btnuploadDoc;
    private javax.swing.JButton btnuploadimage;
    private javax.swing.JComboBox<String> cbxEtat;
    private javax.swing.JComboBox<String> cbxsexeprof;
    private javax.swing.JComboBox<String> cmbprofession;
    private com.toedter.calendar.JDateChooser jDtnaissance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodeprof;
    private javax.swing.JLabel lblimage;
    private javax.swing.JRadioButton rdbEnreg;
    private javax.swing.JRadioButton rdbseach;
    private javax.swing.JTextPane txtadresseprof;
    private javax.swing.JTextField txtcodeprof;
    private javax.swing.JTextField txtemailprof;
    private javax.swing.JFormattedTextField txtmatriculeprof;
    private javax.swing.JTextField txtnomprof;
    private javax.swing.JFormattedTextField txtnumref;
    private javax.swing.JTextField txtprenomprof;
    private javax.swing.JFormattedTextField txttelprof;
    // End of variables declaration//GEN-END:variables
}
