/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.intense.vue;


import com.uni.intense.presentation.InterfaceService;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ServiceReseau;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kelly
 */
public final class PanGestionOPtionsCours extends javax.swing.JPanel {
ServiceReseau ser=new ServiceReseau();
 Contrainte co=new Contrainte();
    /**
     * Creates new form PanOptions
     */
    public PanGestionOPtionsCours() {
        initComponents();
         try {
                    listerOptions();
                    listerCours();
                   rempliroption();
                   PanCours.setVisible(false);
                } catch (NamingException | RemoteException ex) {
                    Logger.getLogger(PanGestionOPtionsCours.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panoption = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnomoption = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbloptions = new javax.swing.JTable();
        PanCours = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbxoptioncours = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxniveau = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxsession = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtnomcours = new javax.swing.JTextField();
        btnajcours = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcours = new javax.swing.JTable();
        rdboptions = new javax.swing.JRadioButton();
        rdbcours = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panoption.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nom Option :");

        txtnomoption.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomoptionKeyTyped(evt);
            }
        });

        btnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apprentissage-en-ligne.png"))); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        tbloptions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(tbloptions);

        javax.swing.GroupLayout panoptionLayout = new javax.swing.GroupLayout(panoption);
        panoption.setLayout(panoptionLayout);
        panoptionLayout.setHorizontalGroup(
            panoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panoptionLayout.createSequentialGroup()
                .addGroup(panoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panoptionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panoptionLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnomoption, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panoptionLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnAjouter)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panoptionLayout.setVerticalGroup(
            panoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panoptionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnomoption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 236, -1, -1));

        PanCours.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Option");

        cbxoptioncours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxoptioncoursActionPerformed(evt);
            }
        });

        jLabel2.setText("Niveau: ");

        cbxniveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbxniveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxniveauActionPerformed(evt);
            }
        });

        jLabel3.setText("Session :");

        cbxsession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cbxsession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsessionActionPerformed(evt);
            }
        });

        jLabel4.setText("Nom Cours :");

        txtnomcours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomcoursKeyTyped(evt);
            }
        });

        btnajcours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apprentissage-en-ligne.png"))); // NOI18N
        btnajcours.setText("Ajouter");
        btnajcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajcoursActionPerformed(evt);
            }
        });

        tblcours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cours", "Options", "Niveau", "Session"
            }
        ));
        jScrollPane1.setViewportView(tblcours);

        javax.swing.GroupLayout PanCoursLayout = new javax.swing.GroupLayout(PanCours);
        PanCours.setLayout(PanCoursLayout);
        PanCoursLayout.setHorizontalGroup(
            PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanCoursLayout.createSequentialGroup()
                .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanCoursLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanCoursLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(197, 197, 197))
                            .addGroup(PanCoursLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(29, 29, 29)
                                .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxniveau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxoptioncours, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanCoursLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PanCoursLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(197, 197, 197))
                                .addComponent(cbxsession, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanCoursLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtnomcours))))
                    .addGroup(PanCoursLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnajcours))
                    .addGroup(PanCoursLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PanCoursLayout.setVerticalGroup(
            PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanCoursLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbxoptioncours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxniveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxsession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnomcours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnajcours)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(PanCours, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 153, -1, -1));

        rdboptions.setSelected(true);
        rdboptions.setText("Gestion Options");
        rdboptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdboptionsActionPerformed(evt);
            }
        });
        add(rdboptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        rdbcours.setText("Gestion Cours");
        rdbcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbcoursActionPerformed(evt);
            }
        });
        add(rdbcours, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gestion des Cours et Options");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(jLabel6)
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(41, 41, 41))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, -1));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
void rempliroption() throws NamingException, RemoteException{
  
                    ArrayList<String> Al=new ArrayList<>();
                    Context cont=new InitialContext();
                  InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
                    Al=  mato.remplirComboOptions();
                     int i=0;
                     cbxoptioncours.removeAllItems();
        for(String dep:Al)
        {
           
            cbxoptioncours.addItem(dep);
            
            i++;
        } 
}
    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        try {
            // TODO add your handling code here:
            String nomoption=txtnomoption.getText().trim().replace("'", "''");
             if(nomoption.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Le nom de l'option est Vide","Erreur",JOptionPane.ERROR_MESSAGE);
            }
             else{
            
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            String mes=mato.EnregistrerOption(nomoption);
            JOptionPane.showMessageDialog(PanGestionOPtionsCours.this,mes);
            listerOptions();
            rempliroption();
             }
        } catch (NamingException ex) {
            Logger.getLogger(PanGestionOPtionsCours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(PanGestionOPtionsCours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void cbxoptioncoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxoptioncoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxoptioncoursActionPerformed

    private void cbxniveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxniveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxniveauActionPerformed

    private void cbxsessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsessionActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_cbxsessionActionPerformed

    private void btnajcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajcoursActionPerformed
        try {
            // TODO add your handling code here:
               
            String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
            String Niveau=cbxniveau.getSelectedItem().toString();
            
            String Session=cbxsession.getSelectedItem().toString();
            String Nomcours=txtnomcours.getText().trim().replace("'", "''");
            if(Nomcours.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Le nom du cours est Vide","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else{
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            String mes=mato.EnregistrerCours(Nom_Opt, Niveau, Session,Nomcours);
            JOptionPane.showMessageDialog(PanGestionOPtionsCours.this,mes);
                  listerCours();
            }
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanGestionOPtionsCours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnajcoursActionPerformed

    private void rdboptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdboptionsActionPerformed
        // TODO add your handling code here:
         if(!rdboptions.isSelected()){
        panoption.setVisible(false);
PanCours.setVisible(true);
 rdbcours .setSelected(true);
        }
         else{
         rdbcours .setSelected(false);
         panoption.setVisible(true);
PanCours.setVisible(false);
         }
    }//GEN-LAST:event_rdboptionsActionPerformed

    private void rdbcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbcoursActionPerformed
        // TODO add your handling code here:
        if(!rdbcours.isSelected()){
        PanCours.setVisible(false);
panoption.setVisible(true);
 rdboptions .setSelected(true);
        }
         
         else{
         rdboptions .setSelected(false);
         panoption.setVisible(false);
PanCours.setVisible(true);
         }
    }//GEN-LAST:event_rdbcoursActionPerformed

    private void txtnomoptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomoptionKeyTyped
        // TODO add your handling code here:
        co.isletter(evt);
    }//GEN-LAST:event_txtnomoptionKeyTyped

    private void txtnomcoursKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomcoursKeyTyped
        // TODO add your handling code here:
         co.isletter(evt);
    }//GEN-LAST:event_txtnomcoursKeyTyped
void listerOptions() throws NamingException, RemoteException{
                      
                   Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            String [][] maliste=mato.ListerOptions();
String[] titre= {"Code de l'option", "Nom de l'option"};
 DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
tbloptions.setModel(model);
 }
void listerCours() throws NamingException, RemoteException{
                  
                   Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            String [][] maliste=mato.ListerCours();
String[] titre= {"Nom du cours", "Nom de l'option","Niveau","Session"};
 DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
tblcours.setModel(model);
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanCours;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnajcours;
    private javax.swing.JComboBox<String> cbxniveau;
    private javax.swing.JComboBox<String> cbxoptioncours;
    private javax.swing.JComboBox<String> cbxsession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panoption;
    private javax.swing.JRadioButton rdbcours;
    private javax.swing.JRadioButton rdboptions;
    private javax.swing.JTable tblcours;
    private javax.swing.JTable tbloptions;
    private javax.swing.JTextField txtnomcours;
    private javax.swing.JTextField txtnomoption;
    // End of variables declaration//GEN-END:variables
}
