/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.intense.vue;



import com.uni.intense.presentation.InterfacePalmares;
import com.uni.intense.service.RapportPalmares;
import com.uni.intense.service.ServiceReseau;
import com.uni.intense.service.TransformerLandscapePdf;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kelly
 */
public class PanlisterPalmares extends javax.swing.JPanel {
ServiceReseau ser=new ServiceReseau();
 String codepal=null;
    /**
     * Creates new form FenlisterPalmares
     */
    public PanlisterPalmares() {
        initComponents();
            btnpdf.setVisible(false);
             String [][] maliste=new String[0][0];
            String[] titre= {"Code", "Nom", "Prenom","Examen Intra","Devoir Intra","Examen Final","Devoir Final","Total Notes","Coefficient"};
              DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtcodepalmares = new javax.swing.JTextField();
        btnrechercher = new javax.swing.JButton();
        btnpdf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnrechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/test.png"))); // NOI18N
        btnrechercher.setText("Lister les Evaluations");
        btnrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherActionPerformed(evt);
            }
        });

        btnpdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf_24px.png"))); // NOI18N
        btnpdf.setText("Imprimer");
        btnpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpdfActionPerformed(evt);
            }
        });

        jLabel1.setText("Code Palmaresse");

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Liste des Evaluations d'un Palmarès");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(445, 445, 445))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(txtcodepalmares, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnrechercher)
                        .addGap(90, 90, 90)
                        .addComponent(btnpdf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodepalmares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrechercher)
                    .addComponent(btnpdf)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherActionPerformed
       try {
            // TODO add your handling code here:
            String codepalmares=txtcodepalmares.getText().trim();
            if(codepalmares.isEmpty()){
            JOptionPane.showMessageDialog(null,"Entrez un code","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else{
             lister(codepalmares);
            }
           
              
      
        } catch (NamingException ex) {
            Logger.getLogger(PanlisterPalmares.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(PanlisterPalmares.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnrechercherActionPerformed

    private void btnpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpdfActionPerformed
        try {
            // TODO add your handling code here:
             
             if(codepal==null){
              JOptionPane.showMessageDialog(null,"Effectuez avant tout une recherche","Erreur",JOptionPane.ERROR_MESSAGE);
             }
             else{
  
            Context cont=new InitialContext();
            InterfacePalmares mato=(InterfacePalmares) cont.lookup(ser.getPalmaresse());
            String [][] maliste=mato.ListerPalmares(codepal);
            String td="";
            String tr1="<tr>";
            String tr2="</tr>";
            int v=0;
            ArrayList Fiche=new ArrayList();
            for(int i=0;i<maliste.length;i++){
                // System.out.println("<tr>");
                Fiche.add(tr1);
                for(int j=0;j<maliste[i].length;j++){
                    // System.out.println("<td>"+maliste[i][j]+"</td>");
                    td="<td>"+maliste[i][j]+"</td>";
                    Fiche.add(td);
                }
                
                Fiche.add(tr2);
                
                //System.out.println("</tr>");
            }
            String Fiche2=Fiche.toString();
            String Fiche3=Fiche2.replace(",", "");
            String Fiche4=Fiche3.replace("[", "");
            String   Tbody=Fiche4.replace("]", "");
            
                ArrayList<String> Al;
             
          
            
            Al=mato.RechercherPalmares(codepal);
           String NomOption=Al.get(0);
                   String NomCours=Al.get(1);
                           String NomVacation=Al.get(2);
                                   String Promotions=Al.get(3);
                                           String Nomsession=Al.get(4);
                                           String Nomniveaux=Al.get(5);
           RapportPalmares html=new RapportPalmares();
     String Html=      html.RapportPalmares(Tbody, NomOption, NomCours, NomVacation, Promotions, Nomsession, Nomniveaux);
                   TransformerLandscapePdf pd=new TransformerLandscapePdf();
                   pd.TransformerLandscapePdf(Html, "palma"+NomCours+NomOption);
                   
            JOptionPane.showMessageDialog(this,"Le Palmares a ete creer avec Succes","Confirmation",JOptionPane.INFORMATION_MESSAGE);
             }   
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanlisterPalmares.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PanlisterPalmares.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnpdfActionPerformed
void lister(String codepalmares) throws NamingException, RemoteException{
  
               
                   Context cont=new InitialContext();
             InterfacePalmares mato=(InterfacePalmares) cont.lookup(ser.getPalmaresse());
            String [][] maliste=mato.ListerPalmares(codepalmares);
String[] titre= {"Code", "Nom", "Prenom","Examen Intra","Devoir Intra","Examen Final","Devoir Final","Total Notes","Coefficient"};
 
int val=0;
try{
String d=maliste[0][0].toString();
val=1;
}
catch(Exception ex){
val=0;
}
if(val==0){
    String aver = "soit ce palmares ne contient pas d'etudiant \n soit Le code de ce palmaresse est Incorecte \n si vous vous souvenez pas du code allez dans le Gestion Palmaresse Pour trouvez le code";
        JOptionPane.showMessageDialog(null,aver,"Erreur",JOptionPane.ERROR_MESSAGE);
     btnpdf.setVisible(false);
     
     codepal=null;
     
     maliste=new String[0][0];
            
              DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
}
else{
    DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
    btnpdf.setVisible(true);
codepal=codepalmares;
}
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpdf;
    private javax.swing.JButton btnrechercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcodepalmares;
    // End of variables declaration//GEN-END:variables
}
