/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.intense.vue;


import com.uni.intense.presentation.InterfaceEvaluationsNormal;
import com.uni.intense.presentation.InterfaceNote;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ServiceReseau;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kelly
 */
public class PanNotes extends javax.swing.JPanel {
ServiceReseau ser=new ServiceReseau();
Contrainte co=new Contrainte();
    /**
     * Creates new form FenEvaluation
     */
    public PanNotes() {
        initComponents();
        InVisible();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblcodeprof = new javax.swing.JLabel();
        txtcodeeval = new javax.swing.JTextField();
        btnlister = new javax.swing.JButton();
        paneval = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panNotes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcoef = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        btnmodif = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1071, 593));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcodeprof.setText("Code Evaluation :");
        jPanel1.add(lblcodeprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        txtcodeeval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodeevalKeyTyped(evt);
            }
        });
        jPanel1.add(txtcodeeval, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 139, -1));

        btnlister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/liste.png"))); // NOI18N
        btnlister.setText("Lister les etudiants");
        btnlister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnlister, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 570, 40));

        paneval.setBackground(new java.awt.Color(255, 255, 255));
        paneval.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        paneval.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        panNotes.setBackground(new java.awt.Color(255, 255, 255));
        panNotes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Code Etudiant :");
        panNotes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, -1));

        txtcode.setEditable(false);
        panNotes.add(txtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 57, 99, -1));

        jLabel9.setText("Note :");
        panNotes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 60, -1, -1));

        jLabel5.setText("Coeficcient");
        panNotes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, -1));

        txtcoef.setEditable(false);
        panNotes.add(txtcoef, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 17, 99, -1));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panNotes.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 57, -1, -1));

        paneval.add(panNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, 347, -1));

        btnmodif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit-icon.png"))); // NOI18N
        btnmodif.setText("Ajouter ou Modifier");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });
        paneval.add(btnmodif, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        add(paneval, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion Notes Des Etudiants");
        jPanel2.add(jLabel1);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnlisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlisterActionPerformed
        // TODO add your handling code here:
        String codeEvaluationsNormal=txtcodeeval.getText().trim();
       if(codeEvaluationsNormal.isEmpty()){
            JOptionPane.showMessageDialog(null,"Entrez un code","Erreur",JOptionPane.ERROR_MESSAGE);
            }
       else{
        try {
            lister(codeEvaluationsNormal);
        } catch (NamingException ex) {
            Logger.getLogger(PanNotes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(PanNotes.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_btnlisterActionPerformed

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
        String codeEvaluationsNormal=txtcodeeval.getText();
            String Id_Etud=txtcode.getText();
            String no=jFormattedTextField1.getText().trim();
            
            if(Id_Etud.isEmpty()){
           JOptionPane.showMessageDialog(null,"Selectionnez un Etudiant","Erreur",JOptionPane.ERROR_MESSAGE);
            }
           else if(no.isEmpty()){
           JOptionPane.showMessageDialog(null,"Entrez une Note","Erreur",JOptionPane.ERROR_MESSAGE);
            }
           else{
            double notenormal=Double.valueOf(jFormattedTextField1.getText().trim());
            
            
             int i_val = (int) Math.round(notenormal);
            String coe= txtcoef.getText();
            int CoeficientNormal=Integer.parseInt(coe);
            if(notenormal>CoeficientNormal){
            JOptionPane.showMessageDialog(PanNotes.this,"la note doit etre inferieur ou egal au coefficient de l'evalution");
            }
            
            else{
            
                try {
            // TODO add your handling code here:
           
       
            Context cont=new InitialContext();
            InterfaceNote mato=(InterfaceNote) cont.lookup(ser.getNote());
             ArrayList<String> Fiche=new ArrayList();
             Fiche=mato.FicheNote(codeEvaluationsNormal, Id_Etud);
             String codenoraml=Fiche.get(0);
             if(codenoraml==null){
             String message=mato.EnregistrerNotesNormalNote(codeEvaluationsNormal, Id_Etud, i_val);
                 JOptionPane.showMessageDialog(PanNotes.this,message);
                 lister(codeEvaluationsNormal);
             }
             else{
                 String message=mato.ModifierNote(codeEvaluationsNormal, Id_Etud, notenormal);
                  JOptionPane.showMessageDialog(PanNotes.this,message);
                    lister(codeEvaluationsNormal);
             }
             
        } catch (NamingException ex) {
            Logger.getLogger(PanNotes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(PanNotes.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
    
           }            
    }//GEN-LAST:event_btnmodifActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ligne=jTable1.getSelectedRow();
        DefaultTableModel model =  (DefaultTableModel) jTable1.getModel();
        txtcode.setText(model.getValueAt(ligne, 0).toString());
        jFormattedTextField1.setText(model.getValueAt(ligne, 3).toString());
        txtcoef.setText(model.getValueAt(ligne, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtcodeevalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodeevalKeyTyped
        // TODO add your handling code here:
        co.isletterdigit(evt);
    }//GEN-LAST:event_txtcodeevalKeyTyped

 void lister(String codeEvaluationsNormal) throws NamingException, RemoteException{
         
                   Context cont=new InitialContext();
             InterfaceEvaluationsNormal mato=(InterfaceEvaluationsNormal) cont.lookup(ser.getEvaluation());
            String [][] maliste=mato.ListerNotes(codeEvaluationsNormal);
            
            
      
String[] titre= {"Code", "Nom", "Prenom","Notes","Coefficient"};



 
int val=0;
try{
String d=maliste[0][0].toString();
val=1;
}
catch(Exception ex){
val=0;
}
if(val==0){
    
        JOptionPane.showMessageDialog(null,"soit cet evaluation ne contient pas d'etudiant \n soit Le code de cette evaluation est Incorecte \n si vous vous souvenez pas du code allez dans le Gestion Evaluation Pour trouvez le code","Erreur",JOptionPane.ERROR_MESSAGE);
        InVisible();
}

else{
Visible();
DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
}
 }
 void Visible(){
 
 paneval.setVisible(true);
 }
 void InVisible(){

 paneval.setVisible(false);
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlister;
    private javax.swing.JButton btnmodif;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcodeprof;
    private javax.swing.JPanel panNotes;
    private javax.swing.JPanel paneval;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtcodeeval;
    private javax.swing.JTextField txtcoef;
    // End of variables declaration//GEN-END:variables
}
