/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.uni.intense.vue;


import com.uni.intense.presentation.InterfacePalmares;
import com.uni.intense.presentation.InterfaceService;
import com.uni.intense.service.Contrainte;
import com.uni.intense.service.ImageFilterJava;
import com.uni.intense.service.ServiceReseau;
import java.awt.Image;
import java.io.File;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author kelly
 */
public class PanPalmares extends javax.swing.JPanel {
ServiceReseau ser=new ServiceReseau();
Contrainte co=new Contrainte();
 public TableRowSorter<TableModel> sorter;
    /**
     * Creates new form FenPalmares
     */
    public PanPalmares() {
        
        initComponents();
        combo();
        lister();  
        remplirpromo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnenregpalmares = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbxoptioncours = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbxniveau = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxsession = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbxcours = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxvacation = new javax.swing.JComboBox<>();
        btnrechercher = new javax.swing.JButton();
        txtcodpal = new javax.swing.JTextField();
        cmbpromo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Annee Promotion :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        btnenregpalmares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ajouter.png"))); // NOI18N
        btnenregpalmares.setText("Enregistrer une Palmares");
        btnenregpalmares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenregpalmaresActionPerformed(evt);
            }
        });
        jPanel1.add(btnenregpalmares, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel17.setText("Option");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cbxoptioncours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxoptioncoursActionPerformed(evt);
            }
        });
        jPanel1.add(cbxoptioncours, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 179, -1));

        jLabel1.setText("Niveau: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        cbxniveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbxniveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxniveauActionPerformed(evt);
            }
        });
        jPanel1.add(cbxniveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 179, -1));

        jLabel2.setText("Session :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        cbxsession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cbxsession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsessionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxsession, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 179, -1));

        jLabel19.setText("Cours");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        cbxcours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcoursActionPerformed(evt);
            }
        });
        jPanel1.add(cbxcours, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 179, -1));

        jLabel3.setText("Vacation :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        cbxvacation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Median", "Matin", "Soir", "Week-End" }));
        cbxvacation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxvacationActionPerformed(evt);
            }
        });
        jPanel1.add(cbxvacation, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        btnrechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chercher.png"))); // NOI18N
        btnrechercher.setText("Trouver le code du palmares");
        btnrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherActionPerformed(evt);
            }
        });
        jPanel1.add(btnrechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        txtcodpal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodpalKeyTyped(evt);
            }
        });
        jPanel1.add(txtcodpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 131, -1));

        jPanel1.add(cmbpromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 138, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 354, 1210, 271));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gestion Palmarès");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jLabel5)
                .addContainerGap(560, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, -1));
    }// </editor-fold>//GEN-END:initComponents
   void remplirpromo(){
 try {
                    
                   
                    ArrayList<String> Al=new ArrayList<>();
                    Context cont=new InitialContext();
                  InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
                    Al=  mato.remplirComboPromotion();
                     int i=0;
        for(String dep:Al)
        {
           
            cmbpromo.addItem(dep);
            
            i++;
        }
                } catch (NamingException ex) {
                    Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(PanAttributionCours.class.getName()).log(Level.SEVERE, null, ex);
                }
}
    void lister(){

    try {
       
        Context cont=new InitialContext();
        InterfacePalmares mato=(InterfacePalmares) cont.lookup(ser.getPalmaresse());
        String [][] maliste=mato.ListerPalmares2();
        String[] titre= { "Code","Options", "Cours","Vacation","Coefficient","Promotion","Date du Creation"};
        
 DefaultTableModel model = new DefaultTableModel(maliste,titre);
    
jTable1.setModel(model);
sorter = new TableRowSorter<>(model);
      jTable1.setRowSorter(sorter);
    } catch (NamingException | RemoteException ex) {
        Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
    }
}

void combo(){

 try {
                    
                
                    ArrayList<String> Al=new ArrayList<>();
                    Context cont=new InitialContext();
                  InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
                    Al=  mato.remplirComboOptions();
                     int i=0;
        for(String dep:Al)
        {
           
            cbxoptioncours.addItem(dep);
            
            i++;
        }
                } catch (NamingException ex) {
                    Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
                }
}
    private void btnenregpalmaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenregpalmaresActionPerformed
        try {
            // TODO add your handling code here:
          
               String NomOption= cbxoptioncours.getSelectedItem().toString().replace("'", "''");
         String NomCours=  cbxcours.getSelectedItem().toString().replace("'", "''");
         
            String NomVacation=cbxvacation.getSelectedItem().toString();

            
           
            String Promotions=cmbpromo.getSelectedItem().toString();
            
           
            Context cont=new InitialContext();
            InterfacePalmares mato=(InterfacePalmares) cont.lookup(ser.getPalmaresse());
         String message=   mato.Palmaresse(NomOption, NomCours, NomVacation, Promotions);
            JOptionPane.showMessageDialog(PanPalmares.this,message);
            lister();
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnenregpalmaresActionPerformed

    private void cbxoptioncoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxoptioncoursActionPerformed
        // TODO add your handling code here:
         try {
        cbxcours.removeAllItems();
        String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
        String Niveau=cbxniveau.getSelectedItem().toString();

        String Session=cbxsession.getSelectedItem().toString();
       

           
            ArrayList<String> Al=new ArrayList<>();
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            Al=  mato.remplirComboCours(Nom_Opt, Niveau, Session);
            int i=0;

            for(String dep:Al)
            {
                cbxcours.addItem(dep);

                i++;
            }
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxoptioncoursActionPerformed

    private void cbxniveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxniveauActionPerformed
        // TODO add your handling code here:
         try {
        cbxcours.removeAllItems();
        String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
        String Niveau=cbxniveau.getSelectedItem().toString();
        String Session=cbxsession.getSelectedItem().toString();
       

            
            ArrayList<String> Al=new ArrayList<>();
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            Al=  mato.remplirComboCours(Nom_Opt, Niveau, Session);
            int i=0;

            for(String dep:Al)
            {
                cbxcours.addItem(dep);

                i++;
            }
        } catch (NamingException | RemoteException ex ) {
            Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cbxniveauActionPerformed

    private void cbxsessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsessionActionPerformed
        // TODO add your handling code here:
         try {

        cbxcours.removeAllItems();
        String Nom_Opt=cbxoptioncours.getSelectedItem().toString();
        String Niveau=cbxniveau.getSelectedItem().toString();

        String Session=cbxsession.getSelectedItem().toString();
       
           
            ArrayList<String> Al=new ArrayList<>();
            Context cont=new InitialContext();
            InterfaceService mato=(InterfaceService) cont.lookup(ser.getService());
            Al=  mato.remplirComboCours(Nom_Opt, Niveau, Session);
            int i=0;

            for(String dep:Al)
            {
                cbxcours.addItem(dep);

                i++;
            }
        } catch (NamingException | RemoteException ex) {
            Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxsessionActionPerformed

    private void cbxcoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcoursActionPerformed
        // TODO add your handling code here:
        //                try{
            //                String Cours=cbxcours.getSelectedItem().toString();
            //                lblcour1.setText(Cours);
            //                }
        //                catch(Exception e){}
    }//GEN-LAST:event_cbxcoursActionPerformed

    private void cbxvacationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxvacationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxvacationActionPerformed

    private void btnrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherActionPerformed
        try {
            // TODO add your handling code here:
            String NomOption= cbxoptioncours.getSelectedItem().toString().replace("'", "''");
            String NomCours=  cbxcours.getSelectedItem().toString().replace("'", "''");
            
            String NomVacation=cbxvacation.getSelectedItem().toString();
            
            
         
            String Promotions=cmbpromo.getSelectedItem().toString();
            
         
            Context cont=new InitialContext();
            InterfacePalmares mato=(InterfacePalmares) cont.lookup(ser.getPalmaresse());
            String message=   mato.RechercherCodePalmaresse(NomOption, NomCours, NomVacation, Promotions);
            
            txtcodpal.setText(message);
            if(message==null){
                    JOptionPane.showMessageDialog(null,"Ce Palmares n'est pas encore creer","Erreur",JOptionPane.ERROR_MESSAGE);
            }
        } catch (NamingException ex) {
            Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(PanPalmares.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnrechercherActionPerformed

    private void txtcodpalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodpalKeyTyped
        // TODO add your handling code here:
         co.isletterdigit(evt);
    }//GEN-LAST:event_txtcodpalKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenregpalmares;
    private javax.swing.JButton btnrechercher;
    private javax.swing.JComboBox<String> cbxcours;
    private javax.swing.JComboBox<String> cbxniveau;
    private javax.swing.JComboBox<String> cbxoptioncours;
    private javax.swing.JComboBox<String> cbxsession;
    private javax.swing.JComboBox<String> cbxvacation;
    private javax.swing.JComboBox<String> cmbpromo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcodpal;
    // End of variables declaration//GEN-END:variables
}
